# Emits the canonical v1 receipt. Keep producer and field names stable for
# current-readiness and downstream evidence consumers.
hepta_browser_emit_receipt() {
report="$(jq -n \
  --arg product "Hepta" \
  --arg runtime "hepta" \
  --arg base_url "$BASE_URL" \
  --arg output_dir "$OUT_DIR" \
  --arg browser_executable "$CHROME_BIN" \
  --arg browser_version "$CHROME_VERSION" \
  --arg browser_executable_sha256 "$CHROME_SHA256" \
  --argjson telegram_live_send_enabled "$telegram_live_send_enabled" \
  --argjson native_post_real_activation_enabled "$native_post_real_activation_enabled" \
  --arg logo_dimensions "$logo_dimensions" \
  --arg logo_sha "$(shasum -a 256 "$logo_png" | awk '{print $1}')" \
  --arg control_ui_js_sha "$served_js_sha" \
  --arg desktop_sha "$(shasum -a 256 "$OUT_DIR/desktop.png" | awk '{print $1}')" \
  --arg narrow_sha "$(shasum -a 256 "$OUT_DIR/narrow.png" | awk '{print $1}')" \
  --arg mobile_sha "$(shasum -a 256 "$OUT_DIR/mobile.png" | awk '{print $1}')" \
  --arg phone320_sha "$(shasum -a 256 "$OUT_DIR/phone320.png" | awk '{print $1}')" \
  --argjson phone320_bytes "$(wc -c <"$OUT_DIR/phone320.png" | tr -d ' ')" \
  --argjson density_qa "$density_qa_json" \
  --argjson progressive_enhancement_qa "$progressive_qa_json" \
  --argjson progressive_enhancement_adversarial_qa "$progressive_adversarial_qa_json" \
  '{
    schema_version:1,
    kind:"hepta-browser-visual-smoke",
    producer:"scripts/hepta-browser-visual-smoke.sh",
    product:$product,
    runtime:$runtime,
    status:"ready",
    base_url:$base_url,
    output_dir:$output_dir,
    browser:"playwright-explicit-chromium-executable",
    browser_executable:$browser_executable,
    browser_version:$browser_version,
    browser_executable_sha256:$browser_executable_sha256,
    checked_text:[
      "data-rust-frontend-renderer=\"hepta-core::control_ui\"",
      "data-no-js-fallback=\"navigation\"",
      "data-progressive-enhancement=\"same-origin-read-only\"",
      "data-control-ui-capability-mode=\"local-read-only\"",
      "data-control-ui-live-adapter-bound=\"false\"",
      "defer src=\"./control-ui.js\"",
      "data-telegram-multi-agent-chat=\"true\"",
      "data-control-ui-product-first=\"true\"",
      "data-control-ui-primary-path=\"telegram-chat-shell\"",
      "data-control-ui-telegram-shell=\"true\"",
      "data-control-ui-top-design-referee=\"liquid-glass-2026-wcag22-320-reflow\"",
      "data-control-ui-harsh-referee=\"2026-06-08-liquid-glass-menus-sidebars-scroll-search\"",
      "data-control-ui-secondary-map=\"collapsed\"",
      "data-control-ui-runtime-rail=\"local-review-safety-evidence\"",
      "data-control-ui-secondary-nav=\"collapsed\"",
      "data-control-ui-composer-product-first=\"true\"",
      "data-mobile-compact-composer=\"true\"",
      "data-control-ui-composer-more=\"collapsed\"",
      "data-control-ui-composer-tools-trigger=\"light-glass\"",
      "data-control-ui-composer-tools-panel=\"light-glass\"",
      "data-control-ui-composer-popover-panel=\"light-glass\"",
      "data-control-ui-topbar-action=\"light-glass\"",
      "data-control-ui-micro-surface",
      "data-control-ui-thread-intro-badge",
      "data-control-ui-status-trust-badge",
      "data-control-ui-work-rail=\"product-first\"",
      "data-control-ui-compact-product-path=\"narrow-mobile\"",
      "data-control-ui-thread-tools-trigger=\"light-glass\"",
      "data-control-ui-thread-tools-panel=\"light-glass\"",
      "data-open-command-palette",
      "id=\"command-palette\"",
      "data-control-ui-command-palette-surface=\"light-glass\"",
      "data-control-ui-command-palette-input=\"light-glass\"",
      "data-control-ui-command-palette-close=\"light-glass\"",
      "data-control-ui-command-palette-result=\"light-glass\""
    ],
    control_ui_product_first_ready:true,
    control_ui_primary_path:"telegram-chat-shell",
    control_ui_telegram_shell_ready:true,
    control_ui_dashboard_cards_hidden:true,
    control_ui_secondary_map_collapsed:true,
    control_ui_runtime_rail_product_first_ready:true,
    control_ui_secondary_nav_collapsed:true,
    control_ui_composer_product_first_ready:true,
    control_ui_work_rail_product_first_ready:true,
    control_ui_compact_product_path_ready:true,
    control_ui_engineering_copy_hidden:true,
    control_ui_top_design_referee_ready:true,
    control_ui_320_reflow_ready:$density_qa.phone320_ready,
    control_ui_default_submenus_closed_ready:$density_qa.default_submenus_closed_ready,
    control_ui_single_submenu_audit_ready:$density_qa.single_submenu_audit_ready,
    control_ui_unavailable_submenu_items_ready:$density_qa.unavailable_submenu_items_ready,
    control_ui_disabled_submenu_item_count:$density_qa.disabled_submenu_item_count,
    control_ui_engineering_status_chips_suppressed_ready:$density_qa.engineering_session_chips_suppressed_ready,
    control_ui_narrow_composer_non_overlap_ready:$density_qa.narrow_composer_non_overlap_ready,
    control_ui_preferred_touch_targets_ready:$density_qa.preferred_touch_targets_ready,
	    control_ui_glass_action_contract_ready:$density_qa.control_glass_action_ready,
	    control_ui_harsh_2026_ready:$density_qa.harsh_referee_ready,
	    control_ui_shallow_light_glass_ready:$density_qa.shallow_light_glass_ready,
	    control_ui_light_theme_semantics_ready:$density_qa.light_theme_semantics_ready,
	    control_ui_stable_content_surface_ready:$density_qa.stable_content_surface_ready,
	    control_ui_native_popover_interaction_ready:$density_qa.native_popover_interaction_ready,
	    control_ui_native_popover_compatibility_source:$density_qa.native_popover_compatibility_source,
	    control_ui_legacy_menu_compatibility_uses_actual_click:$density_qa.legacy_menu_compatibility_uses_actual_click,
	    control_ui_shallow_floating_surface_ready:$density_qa.shallow_floating_surface_ready,
	    control_ui_restrained_optics_ready:$density_qa.restrained_optics_ready,
	    control_ui_restrained_mobile_metadata_ready:$density_qa.restrained_mobile_metadata_ready,
	    control_ui_key_touch_controls_ready:$density_qa.key_touch_controls_ready,
    control_ui_rail_action_icon_ready:$density_qa.rail_action_icon_ready,
    control_ui_icon_buttons_ready:$density_qa.icon_button_ready,
    control_ui_icon_prismatic_control_light_glass_ready:$density_qa.icon_prismatic_control_light_glass_ready,
    control_ui_topbar_action_light_glass_ready:$density_qa.topbar_action_light_glass_ready,
    control_ui_primary_shell_light_glass_ready:$density_qa.primary_shell_light_glass_ready,
	    control_ui_translucent_shell_light_glass_ready:$density_qa.translucent_shell_light_glass_ready,
	    control_ui_refractive_depth_light_glass_ready:$density_qa.refractive_depth_light_glass_ready,
		    control_ui_optical_clarity_light_glass_ready:$density_qa.optical_clarity_light_glass_ready,
		    control_ui_surface_clear_alpha_light_glass_ready:$density_qa.surface_clear_alpha_light_glass_ready,
		    control_ui_substrate_caustic_field_light_glass_ready:$density_qa.substrate_caustic_field_light_glass_ready,
		    control_ui_specular_edge_light_glass_ready:$density_qa.specular_edge_light_glass_ready,
		    control_ui_prismatic_dispersion_light_glass_ready:$density_qa.prismatic_dispersion_light_glass_ready,
		    control_ui_caustic_highlight_light_glass_ready:$density_qa.caustic_highlight_light_glass_ready,
		    control_ui_caustic_depth_shift_light_glass_ready:$density_qa.caustic_depth_shift_light_glass_ready,
			    control_ui_optical_thickness_tiers_light_glass_ready:$density_qa.optical_thickness_tiers_light_glass_ready,
			    control_ui_faceted_reflection_light_glass_ready:$density_qa.faceted_reflection_light_glass_ready,
			    control_ui_beveled_rim_light_glass_ready:$density_qa.beveled_rim_light_glass_ready,
			    control_ui_micro_refraction_light_glass_ready:$density_qa.micro_refraction_light_glass_ready,
			    control_ui_sparkle_glint_light_glass_ready:$density_qa.sparkle_glint_light_glass_ready,
			    control_ui_lens_bloom_light_glass_ready:$density_qa.lens_bloom_light_glass_ready,
			    control_ui_spectral_fusion_light_glass_ready:$density_qa.spectral_fusion_light_glass_ready,
			    control_ui_optical_magnification_light_glass_ready:$density_qa.optical_magnification_light_glass_ready,
			    control_ui_biaxial_magnification_light_glass_ready:$density_qa.biaxial_magnification_light_glass_ready,
			    control_ui_anisotropic_magnification_light_glass_ready:$density_qa.anisotropic_magnification_light_glass_ready,
			    control_ui_phase_separated_refraction_light_glass_ready:$density_qa.phase_separated_refraction_light_glass_ready,
			    control_ui_two_axis_phase_refraction_light_glass_ready:$density_qa.two_axis_phase_refraction_light_glass_ready,
			    control_ui_surface_phase_drift_light_glass_ready:$density_qa.surface_phase_drift_light_glass_ready,
			    control_ui_surface_lens_scale_drift_light_glass_ready:$density_qa.surface_lens_scale_drift_light_glass_ready,
			    control_ui_layer_scale_parallax_light_glass_ready:$density_qa.layer_scale_parallax_light_glass_ready,
			    control_ui_surface_spectral_angle_drift_light_glass_ready:$density_qa.surface_spectral_angle_drift_light_glass_ready,
			    control_ui_surface_glint_focal_drift_light_glass_ready:$density_qa.surface_glint_focal_drift_light_glass_ready,
			    control_ui_composer_glint_focal_decoupling_light_glass_ready:$density_qa.composer_glint_focal_decoupling_light_glass_ready,
			    control_ui_composer_spectral_angle_decoupling_light_glass_ready:$density_qa.composer_spectral_angle_decoupling_light_glass_ready,
			    control_ui_composer_phase_decoupling_light_glass_ready:$density_qa.composer_phase_decoupling_light_glass_ready,
			    control_ui_composer_layer_scale_decoupling_light_glass_ready:$density_qa.composer_layer_scale_decoupling_light_glass_ready,
			    control_ui_chrome_bar_translucency_light_glass_ready:$density_qa.chrome_bar_translucency_light_glass_ready,
			    control_ui_chrome_refractive_skin_light_glass_ready:$density_qa.chrome_refractive_skin_light_glass_ready,
			    control_ui_clear_white_balance_light_glass_ready:$density_qa.clear_white_balance_light_glass_ready,
			    control_ui_chamfer_cut_edge_light_glass_ready:$density_qa.chamfer_cut_edge_light_glass_ready,
			    control_ui_prismatic_cut_edge_light_glass_ready:$density_qa.prismatic_cut_edge_light_glass_ready,
			    control_ui_pane_prismatic_perimeter_light_glass_ready:$density_qa.pane_prismatic_perimeter_light_glass_ready,
			    control_ui_composer_prismatic_control_light_glass_ready:$density_qa.composer_prismatic_control_light_glass_ready,
		    control_ui_menu_triggers_ready:$density_qa.menu_trigger_ready,
	    control_ui_folder_chip_touch_ready:$density_qa.folder_chip_touch_ready,
	    control_ui_folder_chip_label_prismatic_etch_light_glass_ready:$density_qa.folder_chip_label_prismatic_etch_light_glass_ready,
	    control_ui_row_menu_touch_ready:$density_qa.row_menu_touch_ready,
	    control_ui_row_menu_all_rows_ready:$density_qa.row_menu_all_rows_ready,
		    control_ui_row_menu_light_glass_ready:$density_qa.row_menu_light_glass_ready,
	    control_ui_command_palette_ready:$density_qa.command_palette_ready,
	    control_ui_command_palette_surface_light_glass_ready:$density_qa.command_palette_surface_light_glass_ready,
	    control_ui_command_palette_surface_prismatic_perimeter_light_glass_ready:$density_qa.command_palette_surface_prismatic_perimeter_light_glass_ready,
	    control_ui_command_palette_backdrop_caustic_veil_light_glass_ready:$density_qa.command_palette_backdrop_caustic_veil_light_glass_ready,
	    control_ui_command_palette_trigger_light_glass_ready:$density_qa.command_palette_trigger_light_glass_ready,
	    control_ui_command_palette_close_light_glass_ready:$density_qa.command_palette_close_light_glass_ready,
	    control_ui_command_palette_close_prismatic_icon_light_glass_ready:$density_qa.command_palette_close_prismatic_icon_light_glass_ready,
	    control_ui_command_palette_input_light_glass_ready:$density_qa.command_palette_input_light_glass_ready,
			    control_ui_command_palette_input_text_prismatic_etch_light_glass_ready:$density_qa.command_palette_input_text_prismatic_etch_light_glass_ready,
			    control_ui_command_palette_input_placeholder_prismatic_etch_light_glass_ready:$density_qa.command_palette_input_placeholder_prismatic_etch_light_glass_ready,
			    control_ui_command_palette_input_row_prismatic_separator_light_glass_ready:$density_qa.command_palette_input_row_prismatic_separator_light_glass_ready,
			    control_ui_command_palette_results_well_light_glass_ready:$density_qa.command_palette_results_well_light_glass_ready,
			    control_ui_command_palette_results_well_prismatic_rim_light_glass_ready:$density_qa.command_palette_results_well_prismatic_rim_light_glass_ready,
			    control_ui_command_palette_input_icon_light_glass_ready:$density_qa.command_palette_input_icon_light_glass_ready,
			    control_ui_command_palette_input_icon_prismatic_light_glass_ready:$density_qa.command_palette_input_icon_prismatic_light_glass_ready,
			    control_ui_command_palette_item_light_glass_ready:$density_qa.command_palette_item_light_glass_ready,
			    control_ui_command_palette_item_prismatic_rim_light_glass_ready:$density_qa.command_palette_item_prismatic_rim_light_glass_ready,
			    control_ui_command_palette_kind_chip_light_glass_ready:$density_qa.command_palette_kind_chip_light_glass_ready,
			    control_ui_command_palette_item_hover_prismatic_light_glass_ready:$density_qa.command_palette_item_hover_prismatic_light_glass_ready,
			    control_ui_command_palette_item_label_prismatic_etch_light_glass_ready:$density_qa.command_palette_item_label_prismatic_etch_light_glass_ready,
		    control_ui_form_control_title_touch_ready:$density_qa.control_form_control_title_touch_ready,
		    control_ui_chat_row_option_semantic_touch_ready:$density_qa.chat_row_option_semantic_touch_ready,
		    control_ui_rail_chat_row_prismatic_slab_light_glass_ready:$density_qa.rail_chat_row_prismatic_slab_light_glass_ready,
		    control_ui_icon_button_title_match_ready:$density_qa.icon_button_title_match_ready,
    control_ui_menu_trigger_title_match_ready:$density_qa.menu_trigger_title_match_ready,
    control_ui_menu_item_icons_ready:$density_qa.menu_item_icon_ready,
    control_ui_menu_surfaces_ready:$density_qa.menu_surface_ready,
    control_ui_thread_tools_menu_ready:$density_qa.thread_tools_menu_ready,
    control_ui_composer_tools_menu_ready:$density_qa.composer_tools_menu_ready,
    control_ui_composer_tools_trigger_light_glass_ready:$density_qa.composer_tools_trigger_light_glass_ready,
    control_ui_composer_popover_ready:$density_qa.composer_popover_ready,
    control_ui_composer_popover_item_label_prismatic_etch_light_glass_ready:$density_qa.composer_popover_item_label_prismatic_etch_light_glass_ready,
    control_ui_composer_popover_header_prismatic_etch_light_glass_ready:$density_qa.composer_popover_header_prismatic_etch_light_glass_ready,
    control_ui_composer_popover_search_light_glass_ready:$density_qa.composer_popover_search_light_glass_ready,
    control_ui_composer_popover_search_placeholder_prismatic_etch_light_glass_ready:$density_qa.composer_popover_search_placeholder_prismatic_etch_light_glass_ready,
    control_ui_rail_search_light_glass_ready:$density_qa.rail_search_light_glass_ready,
    control_ui_rail_search_placeholder_prismatic_etch_light_glass_ready:$density_qa.rail_search_placeholder_prismatic_etch_light_glass_ready,
    control_ui_rail_prismatic_filter_light_glass_ready:$density_qa.rail_prismatic_filter_light_glass_ready,
    control_ui_micro_surface_light_glass_ready:$density_qa.micro_surface_light_glass_ready,
    control_ui_micro_prismatic_badge_light_glass_ready:$density_qa.micro_prismatic_badge_light_glass_ready,
    control_ui_micro_badge_label_prismatic_etch_light_glass_ready:$density_qa.micro_badge_label_prismatic_etch_light_glass_ready,
    control_ui_message_metadata_prismatic_light_glass_ready:$density_qa.message_metadata_prismatic_light_glass_ready,
    control_ui_thread_subtitle_prismatic_light_glass_ready:$density_qa.thread_subtitle_prismatic_light_glass_ready,
	    control_ui_composer_shortcut_hint_prismatic_light_glass_ready:$density_qa.composer_shortcut_hint_prismatic_light_glass_ready,
	    control_ui_rail_metadata_chip_prismatic_light_glass_ready:$density_qa.rail_metadata_chip_prismatic_light_glass_ready,
	    control_ui_rail_status_count_prismatic_light_glass_ready:$density_qa.rail_status_count_prismatic_light_glass_ready,
	    control_ui_rail_preview_prismatic_etch_light_glass_ready:$density_qa.rail_preview_prismatic_etch_light_glass_ready,
	    control_ui_rail_chat_title_prismatic_etch_light_glass_ready:$density_qa.rail_chat_title_prismatic_etch_light_glass_ready,
	    control_ui_message_body_prismatic_etch_light_glass_ready:$density_qa.message_body_prismatic_etch_light_glass_ready,
	    control_ui_message_speaker_prismatic_chip_light_glass_ready:$density_qa.message_speaker_prismatic_chip_light_glass_ready,
	    control_ui_composer_placeholder_prismatic_etch_light_glass_ready:$density_qa.composer_placeholder_prismatic_etch_light_glass_ready,
	    control_ui_header_title_prismatic_etch_light_glass_ready:$density_qa.header_title_prismatic_etch_light_glass_ready,
    control_ui_message_routing_badge_light_glass_ready:$density_qa.message_routing_badge_light_glass_ready,
    control_ui_thread_intro_badge_light_glass_ready:$density_qa.thread_intro_badge_light_glass_ready,
    control_ui_status_trust_strip_light_glass_ready:$density_qa.status_trust_strip_light_glass_ready,
    control_ui_menu_surface_viewport_guard_ready:$density_qa.menu_surface_viewport_guard_ready,
    control_ui_navigation_icons_ready:$density_qa.nav_icon_ready,
	    control_ui_scroll_edge_ready:$density_qa.scroll_edge_ready,
	    control_ui_microcopy_word_split_guard_ready:$density_qa.microcopy_word_split_guard_ready,
	    control_ui_logo_clip_guard_ready:$density_qa.logo_clip_guard_ready,
	    control_ui_avatar_prismatic_rim_light_glass_ready:$density_qa.avatar_prismatic_rim_light_glass_ready,
	    control_ui_active_chat_readability_ready:$density_qa.active_chat_readability_ready,
	    control_ui_placeholder_readability_ready:$density_qa.placeholder_readability_ready,
	    control_ui_small_control_readability_ready:$density_qa.small_control_readability_ready,
	    control_ui_visible_text_integrity_ready:$density_qa.visible_text_integrity_ready,
	    control_ui_visual_density_qa_ready:true,
    control_ui_browser_error_page_absent:true,
    control_ui_horizontal_overflow_free:true,
    control_ui_progressive_enhancement_ready:true,
    control_ui_unavailable_controls_ready:$progressive_enhancement_qa.unavailable_controls_ready,
    control_ui_unavailable_click_noop_ready:$progressive_enhancement_qa.unavailable_click_noop_ready,
    control_ui_seeded_conversations_ready:$progressive_enhancement_qa.seeded_conversations_ready,
    control_ui_local_json_inspector_ready:$progressive_enhancement_qa.local_json_inspector_ready,
    control_ui_composer_picker_search_ready:$progressive_enhancement_qa.composer_picker_search_ready,
    control_ui_local_draft_insertion_ready:$progressive_enhancement_qa.local_draft_insertion_ready,
    control_ui_local_route_navigation_ready:$progressive_enhancement_qa.local_route_navigation_ready,
    control_ui_readonly_registry_route_count:$progressive_enhancement_qa.registry_route_count,
    control_ui_readonly_registry_successful_route_count:$progressive_enhancement_qa.successful_route_count,
    control_ui_cross_origin_request_count:$progressive_enhancement_qa.cross_origin_request_count,
    control_ui_mutation_endpoint_called:$progressive_enhancement_qa.mutation_endpoint_called,
    control_ui_live_adapter_bound:$progressive_enhancement_qa.live_adapter_bound,
    control_ui_progressive_adversarial_ready:($progressive_enhancement_adversarial_qa.status == "ready"),
    density_qa:$density_qa,
    progressive_enhancement_qa:$progressive_enhancement_qa,
    progressive_enhancement_adversarial_qa:$progressive_enhancement_adversarial_qa,
    checked_assets:[
		      {path:"/styles.css", markers:[".tg-conversation-rail",".tg-thread-panel",".command-palette","safe-area-inset-bottom","mrog","data-control-ui-compact-product-path","data-control-ui-primary-shell-light-glass","crs","cwb","cce","pce","ppe","cpe","mpb","ipc","avr","rpf","rcs","mmp","tsp","csh","rms","hte","rsc","rpe","mbp","bsp","rsp","fcp","strong){filter","--x:0 1px #fff6","text-shadow:var(--x)","rdlg","oclg","data-control-ui-tspcfrg","dsc","mecs","cmv","ctlg","cplg","cpsg","rmlg","ttlg","bmslg","mslg","tiblg","stslg","talg","body[data-view=chat] .hepta-secondary-map{display:none}","gar26","cps","cpis","cpt","cpc","cpir","cph","cprw","cprr","cpkc","cpilg","data-control-ui-command-palette-input=light-glass","data-control-ui-command-palette-result=light-glass"]},
      {path:"/assets/hepta-agent-logo.png", dimensions:$logo_dimensions, sha256:$logo_sha}
      ,{path:"/control-ui.js", sha256:$control_ui_js_sha, source_bound:true, etag_bound:true, inline_script:false}
    ],
    telegram_live_send_enabled:$telegram_live_send_enabled,
    native_post_real_activation_enabled:$native_post_real_activation_enabled,
    screenshots:[
      {name:"desktop", viewport:"1365x900", sha256:$desktop_sha},
      {name:"narrow", viewport:"768x900", sha256:$narrow_sha},
      {name:"mobile", viewport:"500x844", sha256:$mobile_sha},
      {name:"phone320", viewport:"320x844", sha256:$phone320_sha, bytes:$phone320_bytes, path:($output_dir + "/phone320.png")}
    ],
    side_effects:{
      telegram_read:false,
      telegram_send:false,
      native_post_real_mutation:false,
      provider_invoked:false
    }
  }')"

printf '%s\n' "$report"

if [[ -n "$REPORT_PATH" ]]; then
  hepta_safe_output_atomic_write_text "$REPORT_PATH" "$report" || {
    echo "could not atomically write browser smoke receipt" >&2
    return 1
  }
fi
}
