#![forbid(unsafe_code)]

mod advisory_observation;
mod cognitive;
mod extension;
mod framing;
mod local_lifecycle;
mod local_rehydration;
mod local_runtime;
mod observation;

pub use advisory_observation::HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_NAMESPACE;
pub use advisory_observation::HEPTA_MEMORY_SHADOW_ADVISORY_OBSERVATION_SCHEMA_VERSION;
pub use advisory_observation::SHADOW_ADVISORY_OBSERVATION_EXTERNAL_EFFECTS;
pub use advisory_observation::SHADOW_ADVISORY_OBSERVATION_KG_WRITE_AUTHORITY;
pub use advisory_observation::SHADOW_ADVISORY_OBSERVATION_RUNTIME_CONSUMER;
pub use advisory_observation::ShadowAdvisoryHostInput;
pub use advisory_observation::ShadowAdvisoryObservationError;
pub use advisory_observation::ShadowAdvisoryObservationInput;
pub use advisory_observation::ShadowAdvisoryObservationReason;
pub use advisory_observation::ShadowAdvisoryTurnObservation;
pub use advisory_observation::observe_shadow_advisory;
pub use advisory_observation::observe_shadow_advisory_input;
pub use advisory_observation::require_shadow_advisory_observation;
pub use advisory_observation::shadow_advisory_turn_observation;
pub use extension::HeptaMemoryExtension;
pub use extension::HeptaMemoryFeatureFlags;
pub use extension::HeptaMemoryThreadConfig;
pub use extension::install;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_EXTERNAL_EFFECTS;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_KG_WRITE_AUTHORITY;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_NAMESPACE;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_PRODUCTION_CALLER;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_PROVIDER_EFFECTS;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_ROUTING_AUTHORITY;
pub use local_rehydration::LOCAL_REHYDRATION_HOST_SCHEMA_VERSION;
pub use local_rehydration::LocalRehydrationHostError;
pub use local_rehydration::LocalRehydrationHostInput;
pub use local_rehydration::LocalRehydrationHostRead;
pub use local_rehydration::read_local_rehydration_for_turn;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_EXTERNAL_EFFECTS;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_KG_WRITE_AUTHORITY;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_NAMESPACE;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_PRODUCTION_CALLER;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_PROVIDER_EFFECTS;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_ROUTING_AUTHORITY;
pub use local_runtime::LOCAL_REHYDRATION_RUNTIME_SCHEMA_VERSION;
pub use local_runtime::LocalRehydrationRuntimeDisposition;
pub use local_runtime::LocalRehydrationRuntimeError;
pub use local_runtime::LocalRehydrationRuntimePlan;
pub use local_runtime::prepare_local_rehydration_runtime;
pub use observation::HEPTA_MEMORY_SHADOW_OBSERVATION_SCHEMA_VERSION;
pub use observation::ShadowRecallTurnObservation;
pub use observation::ShadowRecallTurnObservationId;
pub use observation::ShadowRecallTurnReason;
pub use observation::shadow_recall_turn_observation;
