use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(transparent)]
pub(crate) struct NativeReportId(pub(crate) u16);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct NativeReportRouteSpec {
    path: &'static str,
    report_id: NativeReportId,
}

#[rustfmt::skip]
const NATIVE_REPORT_ROUTES: &[NativeReportRouteSpec] = &[
    NativeReportRouteSpec { path: "/api/control-ui", report_id: NativeReportId(6) },
    NativeReportRouteSpec { path: "/api/ui-contract-audit", report_id: NativeReportId(7) },
    NativeReportRouteSpec { path: "/api/operator-snapshot", report_id: NativeReportId(245) },
    NativeReportRouteSpec { path: "/api/operator-security", report_id: NativeReportId(247) },
    NativeReportRouteSpec { path: "/api/hepta-merge-completion", report_id: NativeReportId(14) },
    NativeReportRouteSpec { path: "/api/hepta-cli-command-inventory", report_id: NativeReportId(15) },
    NativeReportRouteSpec { path: "/api/hepta-provider-metadata-inventory", report_id: NativeReportId(16) },
    NativeReportRouteSpec { path: "/api/hepta-runtime-session-dry-run-inventory", report_id: NativeReportId(17) },
    NativeReportRouteSpec { path: "/api/hepta-context-recall-worker-scheduler-handoff", report_id: NativeReportId(18) },
    NativeReportRouteSpec { path: "/api/hepta-channel-adapter-status-inventory", report_id: NativeReportId(19) },
    NativeReportRouteSpec { path: "/api/hepta-local-tooling-content-inventory", report_id: NativeReportId(20) },
    NativeReportRouteSpec { path: "/api/hepta-systems-tool-registry-inventory", report_id: NativeReportId(21) },
    NativeReportRouteSpec { path: "/api/hepta-systems-workflow-definition-registry", report_id: NativeReportId(22) },
    NativeReportRouteSpec { path: "/api/hepta-memory-capability-absorption-inventory", report_id: NativeReportId(23) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-readiness", report_id: NativeReportId(24) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-readiness", report_id: NativeReportId(25) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled", report_id: NativeReportId(26) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-no-persistence", report_id: NativeReportId(27) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-authority-denial", report_id: NativeReportId(28) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-trusted-operator-packet-separation", report_id: NativeReportId(29) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-trusted-operator-packet-intake-precondition", report_id: NativeReportId(30) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-trusted-operator-packet-partial-precondition-denial-matrix", report_id: NativeReportId(31) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-trusted-operator-packet-complete-precondition-authority-denial", report_id: NativeReportId(32) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-approved-shadow-context-activation-execution-controlled-readback-receipt-trusted-operator-packet-complete-precondition-operator-approval-lane-separation", report_id: NativeReportId(33) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-memory-live-mutation-durable-lane", report_id: NativeReportId(34) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-hepta-intelligence-context-attachment-lane", report_id: NativeReportId(35) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-kg-prompt-preview-read-only-adapter-lane", report_id: NativeReportId(36) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-activation-truth-index", report_id: NativeReportId(37) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-operator-acknowledgement-non-acceptance", report_id: NativeReportId(38) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-request-denial-matrix", report_id: NativeReportId(39) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-noop-handoff", report_id: NativeReportId(40) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-no-persistence", report_id: NativeReportId(41) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-replay-idempotency-denial", report_id: NativeReportId(42) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-ordering-monotonicity-denial", report_id: NativeReportId(43) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-cancellation-supersession-denial", report_id: NativeReportId(44) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-audit-trail-immutable-evidence-denial", report_id: NativeReportId(45) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(46) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-export-query-observability-denial", report_id: NativeReportId(47) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(48) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(49) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-terminal-operator-decision-public-claim-non-promotion-denial", report_id: NativeReportId(50) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-runtime-provider-router-activation-command-result-receipt-release-artifact-publication-denial", report_id: NativeReportId(51) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-kg-prompt-payload-materialization-lane", report_id: NativeReportId(52) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-kg-prompt-payload-acceptance-receipt-lane", report_id: NativeReportId(53) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-kg-prompt-payload-readback-audit-receipt-lane", report_id: NativeReportId(54) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-context-handoff-acceptance-lane", report_id: NativeReportId(55) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-context-handoff-receipt-audit-lane", report_id: NativeReportId(56) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-bounded-provider-router-injection-precondition-lane", report_id: NativeReportId(57) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-bounded-provider-router-injection-dry-run-envelope-lane", report_id: NativeReportId(58) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-bounded-provider-router-injection-dry-run-envelope-readback-audit-receipt-lane", report_id: NativeReportId(59) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-approved-bounded-provider-router-injection-dry-run-envelope-readback-audit-receipt-acknowledgement-no-op-handoff-lane", report_id: NativeReportId(60) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-single-budget-dispatch-dry-run-noop-receipt", report_id: NativeReportId(61) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-readback-index-no-persistence", report_id: NativeReportId(62) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-non-acceptance", report_id: NativeReportId(63) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-request-denial-matrix", report_id: NativeReportId(64) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-noop-handoff", report_id: NativeReportId(65) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-no-persistence", report_id: NativeReportId(66) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-replay-idempotency-denial", report_id: NativeReportId(67) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-ordering-monotonicity-denial", report_id: NativeReportId(68) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-cancellation-supersession-denial", report_id: NativeReportId(69) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-audit-trail-immutable-evidence-denial", report_id: NativeReportId(70) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(71) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-export-query-observability-denial", report_id: NativeReportId(72) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(73) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(74) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-terminal-operator-decision-public-claim-non-promotion-denial", report_id: NativeReportId(75) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-release-artifact-publication-denial", report_id: NativeReportId(76) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-enablement-operator-canary-controlled-request-harness-operator-review-acknowledgement-activation-command-result-receipt-release-artifact-publication-result-receipt-no-persistence", report_id: NativeReportId(77) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-readiness-index-replay-idempotency-denial", report_id: NativeReportId(78) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template", report_id: NativeReportId(79) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-non-acceptance-authority-replay-denial", report_id: NativeReportId(80) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-field-validation-denial", report_id: NativeReportId(81) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-section-completion-non-acceptance", report_id: NativeReportId(82) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-assembly-non-acceptance", report_id: NativeReportId(83) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-non-persistence", report_id: NativeReportId(84) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-replay-idempotency-denial", report_id: NativeReportId(85) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-ordering-monotonicity-denial", report_id: NativeReportId(86) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-cancellation-supersession-denial", report_id: NativeReportId(87) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-audit-trail-immutable-evidence-denial", report_id: NativeReportId(88) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(89) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-export-query-observability-denial", report_id: NativeReportId(90) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-redaction-privacy-payload-exposure-denial", report_id: NativeReportId(91) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-operator-briefing-non-persistence", report_id: NativeReportId(92) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-final-acknowledgement-non-acceptance", report_id: NativeReportId(93) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-terminal-decision-status-promotion-denial", report_id: NativeReportId(94) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-denial", report_id: NativeReportId(95) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-no-persistence", report_id: NativeReportId(96) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-replay-idempotency-denial", report_id: NativeReportId(97) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-ordering-monotonicity-denial", report_id: NativeReportId(98) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-cancellation-supersession-denial", report_id: NativeReportId(99) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-audit-trail-immutable-evidence-denial", report_id: NativeReportId(100) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(101) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-export-query-observability-denial", report_id: NativeReportId(102) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(103) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(104) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-decision-status-promotion-denial", report_id: NativeReportId(105) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-public-claim-status-exposure-denial", report_id: NativeReportId(106) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-queue-artifact-availability-status-denial", report_id: NativeReportId(107) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-external-delivery-non-persistence-denial", report_id: NativeReportId(108) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-query-export-observability-denial", report_id: NativeReportId(109) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-package-release-channel-status-exposure-denial", report_id: NativeReportId(110) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-distribution-artifact-manifest-status-denial", report_id: NativeReportId(111) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-distribution-signing-notarization-surface-denial", report_id: NativeReportId(112) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-denial", report_id: NativeReportId(113) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-no-persistence-denial", report_id: NativeReportId(114) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-replay-idempotency-denial", report_id: NativeReportId(115) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-ordering-monotonicity-denial", report_id: NativeReportId(116) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-cancellation-supersession-denial", report_id: NativeReportId(117) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-audit-trail-immutable-evidence-denial", report_id: NativeReportId(118) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(119) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-export-query-observability-denial", report_id: NativeReportId(120) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(121) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(122) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-terminal-decision-status-promotion-denial", report_id: NativeReportId(123) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-intent-consent-reconfirmation-denial", report_id: NativeReportId(124) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-binding-denial", report_id: NativeReportId(125) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-replay-cross-binding-denial", report_id: NativeReportId(126) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-denial", report_id: NativeReportId(127) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-denial", report_id: NativeReportId(128) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-ordering-monotonicity-denial", report_id: NativeReportId(129) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-cancellation-supersession-denial", report_id: NativeReportId(130) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-audit-evidence-denial", report_id: NativeReportId(131) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-retention-expiry-garbage-collection-denial", report_id: NativeReportId(132) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-export-query-observability-denial", report_id: NativeReportId(133) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(134) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(135) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-terminal-decision-status-promotion-denial", report_id: NativeReportId(136) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-terminal-public-claim-status-exposure-denial", report_id: NativeReportId(137) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-reconfirmation-denial", report_id: NativeReportId(138) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-operator-readiness-packet-template-packet-acceptance-receipt-release-publication-result-receipt-terminal-distribution-delivery-receipt-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-persistence-denial", report_id: NativeReportId(139) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-no-persistence-denial", report_id: NativeReportId(140) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-replay-idempotency-denial", report_id: NativeReportId(141) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-ordering-monotonicity-denial", report_id: NativeReportId(142) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-cancellation-supersession-denial", report_id: NativeReportId(143) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-audit-evidence-denial", report_id: NativeReportId(144) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(145) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-export-query-observability-denial", report_id: NativeReportId(146) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(147) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(148) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-terminal-public-claim-status-exposure-denial", report_id: NativeReportId(149) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-terminal-public-claim-delivery-readback-denial", report_id: NativeReportId(150) },
    NativeReportRouteSpec { path: "/api/hepta-memory-intelligence-kg-full-live-activation-artifact-download-install-affordance-result-receipt-operator-identity-session-revocation-logout-replay-reinstatement-operator-intent-consent-evidence-artifact-signing-receipt-release-public-artifact-publication-denial", report_id: NativeReportId(151) },
    NativeReportRouteSpec { path: "/api/hepta-minimal-memory-canary-scoped-operator-packet-write-readback-rollback-idempotency-receipt", report_id: NativeReportId(152) },
    NativeReportRouteSpec { path: "/api/hepta-intelligence-bounded-context-attachment-preview-readback", report_id: NativeReportId(153) },
    NativeReportRouteSpec { path: "/api/hepta-bounded-intelligence-context-handoff-prompt-preview-boundary", report_id: NativeReportId(154) },
    NativeReportRouteSpec { path: "/api/hepta-kg-read-only-adapter-shadow-rank-canary", report_id: NativeReportId(155) },
    NativeReportRouteSpec { path: "/api/hepta-provider-router-dry-run-envelope-readback-audit", report_id: NativeReportId(156) },
    NativeReportRouteSpec { path: "/api/hepta-activation-evidence-no-write-provider-router-dry-run-boundary", report_id: NativeReportId(157) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-explicit-approval-evidence-no-invocation-boundary", report_id: NativeReportId(158) },
    NativeReportRouteSpec { path: "/api/hepta-full-live-activation-closure-index", report_id: NativeReportId(159) },
    NativeReportRouteSpec { path: "/api/hepta-upstream-codex-latest-multisurface-absorption", report_id: NativeReportId(215) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-separate-approval-slice-preflight", report_id: NativeReportId(216) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-packet-review-acceptance-denial-preflight", report_id: NativeReportId(217) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-acceptance-artifact-precondition", report_id: NativeReportId(218) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-nonce-session-command-binding-preflight", report_id: NativeReportId(219) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-envelope-preflight", report_id: NativeReportId(220) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-no-persistence", report_id: NativeReportId(221) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-replay-idempotency-denial", report_id: NativeReportId(222) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-ordering-monotonicity-denial", report_id: NativeReportId(223) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-cancellation-supersession-denial", report_id: NativeReportId(224) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-audit-immutable-evidence-denial", report_id: NativeReportId(225) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-retention-expiry-garbage-collection-denial", report_id: NativeReportId(226) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-export-query-observability-denial", report_id: NativeReportId(227) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-operator-facing-summary-briefing-non-persistence-denial", report_id: NativeReportId(228) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-final-operator-acknowledgement-non-acceptance-denial", report_id: NativeReportId(229) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-terminal-operator-decision-public-claim-non-promotion-denial", report_id: NativeReportId(230) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-terminal-public-claim-status-exposure-denial", report_id: NativeReportId(231) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-invocation-operator-approval-final-authorization-dry-run-result-receipt-terminal-public-claim-delivery-readback-denial", report_id: NativeReportId(232) },
    NativeReportRouteSpec { path: "/api/hepta-first-model-positive-approval-packet-boundary", report_id: NativeReportId(233) },
    NativeReportRouteSpec { path: "/api/hepta-scoped-memory-canary-durable-receipt-boundary", report_id: NativeReportId(234) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-approval-packet-boundary", report_id: NativeReportId(160) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-preflight-boundary", report_id: NativeReportId(161) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-denial-matrix-boundary", report_id: NativeReportId(162) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-no-write-sink-contract-boundary", report_id: NativeReportId(163) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-write-enable-fixture-boundary", report_id: NativeReportId(164) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-post-write-validation-dry-run-boundary", report_id: NativeReportId(165) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-post-write-operator-acceptance-denial-boundary", report_id: NativeReportId(166) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-closure-denial-boundary", report_id: NativeReportId(167) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-no-op-handoff-boundary", report_id: NativeReportId(168) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-no-persistence-boundary", report_id: NativeReportId(169) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-replay-idempotency-denial-boundary", report_id: NativeReportId(170) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-ordering-monotonicity-denial-boundary", report_id: NativeReportId(171) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-cancellation-supersession-denial-boundary", report_id: NativeReportId(172) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-audit-trail-immutable-evidence-denial-boundary", report_id: NativeReportId(173) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-retention-expiry-garbage-collection-denial-boundary", report_id: NativeReportId(174) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-export-query-observability-denial-boundary", report_id: NativeReportId(175) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-operator-facing-summary-briefing-non-persistence-denial-boundary", report_id: NativeReportId(176) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-final-operator-acknowledgement-non-acceptance-denial-boundary", report_id: NativeReportId(177) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-terminal-operator-decision-public-claim-non-promotion-denial-boundary", report_id: NativeReportId(178) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-activation-command-result-receipt-release-artifact-publication-denial-boundary", report_id: NativeReportId(179) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-memory-real-write-canary-operator-approval-packet-nonce-command-dry-run-boundary", report_id: NativeReportId(180) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-memory-real-write-canary-readback-validation-dry-run-boundary", report_id: NativeReportId(181) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-memory-real-write-canary-rollback-tombstone-dry-run-boundary", report_id: NativeReportId(182) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-operator-approval-nonce-command-accepted-gate-boundary", report_id: NativeReportId(183) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-wal-receipt-binding-boundary", report_id: NativeReportId(184) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-post-write-readback-binding-boundary", report_id: NativeReportId(185) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-rollback-tombstone-proof-boundary", report_id: NativeReportId(186) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-execution-boundary", report_id: NativeReportId(187) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-wal-receipt-persistence-boundary", report_id: NativeReportId(188) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-readback-receipt-acceptance-boundary", report_id: NativeReportId(189) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-rollback-receipt-acceptance-boundary", report_id: NativeReportId(190) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-tombstone-cleanup-acceptance-boundary", report_id: NativeReportId(191) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-plan-boundary", report_id: NativeReportId(192) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-preflight-boundary", report_id: NativeReportId(193) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-guarded-execution-readiness-boundary", report_id: NativeReportId(194) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-guarded-execution-boundary", report_id: NativeReportId(195) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-single-shot-execution-boundary", report_id: NativeReportId(196) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-receipt-acceptance-boundary", report_id: NativeReportId(197) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-minimal-scoped-memory-real-write-canary-durable-store-write-rollback-tombstone-zero-residue-acceptance-boundary", report_id: NativeReportId(198) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-preflight-boundary", report_id: NativeReportId(199) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-operator-packet-acceptance-boundary", report_id: NativeReportId(200) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-operator-packet-acceptance-receipt-boundary", report_id: NativeReportId(201) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-envelope-boundary", report_id: NativeReportId(202) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-boundary", report_id: NativeReportId(203) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-replay-idempotency-denial-boundary", report_id: NativeReportId(204) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-ordering-monotonicity-denial-boundary", report_id: NativeReportId(205) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-cancellation-supersession-denial-boundary", report_id: NativeReportId(206) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-audit-trail-immutable-evidence-denial-boundary", report_id: NativeReportId(207) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-retention-expiry-garbage-collection-denial-boundary", report_id: NativeReportId(208) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-export-query-observability-denial-boundary", report_id: NativeReportId(209) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-operator-facing-summary-briefing-non-persistence-denial-boundary", report_id: NativeReportId(210) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-final-operator-acknowledgement-non-acceptance-denial-boundary", report_id: NativeReportId(211) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-terminal-operator-decision-public-claim-non-promotion-denial-boundary", report_id: NativeReportId(212) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-release-artifact-publication-denial-boundary", report_id: NativeReportId(213) },
    NativeReportRouteSpec { path: "/api/hepta-memory-live-mutation-operator-write-execution-scoped-production-durable-memory-write-dry-run-execution-result-receipt-release-artifact-publication-result-receipt-no-persistence-boundary", report_id: NativeReportId(214) },
    NativeReportRouteSpec { path: "/api/hepta-release-hardening-status-gate", report_id: NativeReportId(235) },
    NativeReportRouteSpec { path: "/api/hepta-provider-channel-dry-run-plan", report_id: NativeReportId(236) },
    NativeReportRouteSpec { path: "/api/hepta-native-packaging-gate", report_id: NativeReportId(237) },
    NativeReportRouteSpec { path: "/api/hepta-legacy-compatibility-closure", report_id: NativeReportId(238) },
    NativeReportRouteSpec { path: "/api/hepta-public-ga-operator-approval-packet", report_id: NativeReportId(239) },
    NativeReportRouteSpec { path: "/api/hepta-public-ga-readiness", report_id: NativeReportId(240) },
    NativeReportRouteSpec { path: "/api/hepta-core-fusion-readiness", report_id: NativeReportId(241) },
    NativeReportRouteSpec { path: "/api/hepta-name-repository-closure", report_id: NativeReportId(242) },
    NativeReportRouteSpec { path: "/api/hepta-engine-dependency-closure", report_id: NativeReportId(243) },
    NativeReportRouteSpec { path: "/api/hepta-engine-adapter-boundary", report_id: NativeReportId(244) },
    NativeReportRouteSpec { path: "/api/hepta-codex-engine-adapter-boundary", report_id: NativeReportId(244) },
    NativeReportRouteSpec { path: "/api/native-post-execution-readiness", report_id: NativeReportId(248) },
    NativeReportRouteSpec { path: "/api/native-post-execution-stores", report_id: NativeReportId(249) },
    NativeReportRouteSpec { path: "/api/native-post-activation-plan", report_id: NativeReportId(250) },
    NativeReportRouteSpec { path: "/api/native-post-rollout-evidence", report_id: NativeReportId(251) },
    NativeReportRouteSpec { path: "/api/native-post-gray-release-evidence", report_id: NativeReportId(252) },
    NativeReportRouteSpec { path: "/api/ui-action-plan/gateway-dispatch", report_id: NativeReportId(9) },
    NativeReportRouteSpec { path: "/api/operator-console", report_id: NativeReportId(246) },
    NativeReportRouteSpec { path: "/api/sessions", report_id: NativeReportId(253) },
    NativeReportRouteSpec { path: "/api/session-activity", report_id: NativeReportId(254) },
    NativeReportRouteSpec { path: "/api/transcript", report_id: NativeReportId(255) },
    NativeReportRouteSpec { path: "/api/approvals", report_id: NativeReportId(256) },
    NativeReportRouteSpec { path: "/api/policy", report_id: NativeReportId(257) },
    NativeReportRouteSpec { path: "/api/subagent-observatory", report_id: NativeReportId(261) },
    NativeReportRouteSpec { path: "/api/events", report_id: NativeReportId(258) },
    NativeReportRouteSpec { path: "/api/events-report", report_id: NativeReportId(259) },
    NativeReportRouteSpec { path: "/api/activity", report_id: NativeReportId(260) },
    NativeReportRouteSpec { path: "/api/gateway-runtime", report_id: NativeReportId(5) },
    NativeReportRouteSpec { path: "/api/gateway-dispatch", report_id: NativeReportId(8) },
    NativeReportRouteSpec { path: "/api/telegram-production-readiness", report_id: NativeReportId(274) },
    NativeReportRouteSpec { path: "/api/telegram-delivery-ledger", report_id: NativeReportId(275) },
    NativeReportRouteSpec { path: "/api/telegram-owner-handoff", report_id: NativeReportId(276) },
    NativeReportRouteSpec { path: "/api/gateway-ledger", report_id: NativeReportId(262) },
    NativeReportRouteSpec { path: "/api/gateway-retry-dead-letter", report_id: NativeReportId(263) },
    NativeReportRouteSpec { path: "/api/multi-agent-runtime", report_id: NativeReportId(264) },
    NativeReportRouteSpec { path: "/api/config", report_id: NativeReportId(265) },
    NativeReportRouteSpec { path: "/api/optional-configs", report_id: NativeReportId(266) },
    NativeReportRouteSpec { path: "/api/external-agent-benchmark", report_id: NativeReportId(10) },
    NativeReportRouteSpec { path: "/", report_id: NativeReportId(0) },
    NativeReportRouteSpec { path: "/index.html", report_id: NativeReportId(0) },
    NativeReportRouteSpec { path: "/styles.css", report_id: NativeReportId(1) },
    NativeReportRouteSpec { path: "/gateway-status", report_id: NativeReportId(2) },
    NativeReportRouteSpec { path: "/gateway-status.html", report_id: NativeReportId(2) },
    NativeReportRouteSpec { path: "/native-gateway.html", report_id: NativeReportId(2) },
    NativeReportRouteSpec { path: "/health", report_id: NativeReportId(3) },
    NativeReportRouteSpec { path: "/api/health", report_id: NativeReportId(3) },
    NativeReportRouteSpec { path: "/api/watchdog-state", report_id: NativeReportId(4) },
    NativeReportRouteSpec { path: "/api/native-gateway", report_id: NativeReportId(5) },
    NativeReportRouteSpec { path: "/api/gateway-replacement-readiness", report_id: NativeReportId(11) },
    NativeReportRouteSpec { path: "/api/gateway-live-activation-plan", report_id: NativeReportId(12) },
    NativeReportRouteSpec { path: "/api/control-ui-route-parity", report_id: NativeReportId(13) },
    NativeReportRouteSpec { path: "/api/telegram-plugin", report_id: NativeReportId(267) },
    NativeReportRouteSpec { path: "/api/telegram-model-turn-plan", report_id: NativeReportId(268) },
    NativeReportRouteSpec { path: "/api/telegram-model-bridge", report_id: NativeReportId(269) },
    NativeReportRouteSpec { path: "/api/telegram-send-plan", report_id: NativeReportId(270) },
    NativeReportRouteSpec { path: "/api/telegram-drain-once", report_id: NativeReportId(271) },
    NativeReportRouteSpec { path: "/api/telegram-poll-loop", report_id: NativeReportId(272) },
    NativeReportRouteSpec { path: "/api/telegram-live-soak", report_id: NativeReportId(273) },
    NativeReportRouteSpec { path: "/api/telegram-live-soak-status", report_id: NativeReportId(273) },
    NativeReportRouteSpec { path: "/api/telegram-cursor", report_id: NativeReportId(277) },
];

#[rustfmt::skip]
const NATIVE_REPORT_KEYS: &[&str] = &[
    "native_report_000", "native_report_001", "native_report_002", "native_report_003", "native_report_004", "native_report_005", "native_report_006", "native_report_007",
    "native_report_008", "native_report_009", "native_report_010", "native_report_011", "native_report_012", "native_report_013", "native_report_014", "native_report_015",
    "native_report_016", "native_report_017", "native_report_018", "native_report_019", "native_report_020", "native_report_021", "native_report_022", "native_report_023",
    "native_report_024", "native_report_025", "native_report_026", "native_report_027", "native_report_028", "native_report_029", "native_report_030", "native_report_031",
    "native_report_032", "native_report_033", "native_report_034", "native_report_035", "native_report_036", "native_report_037", "native_report_038", "native_report_039",
    "native_report_040", "native_report_041", "native_report_042", "native_report_043", "native_report_044", "native_report_045", "native_report_046", "native_report_047",
    "native_report_048", "native_report_049", "native_report_050", "native_report_051", "native_report_052", "native_report_053", "native_report_054", "native_report_055",
    "native_report_056", "native_report_057", "native_report_058", "native_report_059", "native_report_060", "native_report_061", "native_report_062", "native_report_063",
    "native_report_064", "native_report_065", "native_report_066", "native_report_067", "native_report_068", "native_report_069", "native_report_070", "native_report_071",
    "native_report_072", "native_report_073", "native_report_074", "native_report_075", "native_report_076", "native_report_077", "native_report_078", "native_report_079",
    "native_report_080", "native_report_081", "native_report_082", "native_report_083", "native_report_084", "native_report_085", "native_report_086", "native_report_087",
    "native_report_088", "native_report_089", "native_report_090", "native_report_091", "native_report_092", "native_report_093", "native_report_094", "native_report_095",
    "native_report_096", "native_report_097", "native_report_098", "native_report_099", "native_report_100", "native_report_101", "native_report_102", "native_report_103",
    "native_report_104", "native_report_105", "native_report_106", "native_report_107", "native_report_108", "native_report_109", "native_report_110", "native_report_111",
    "native_report_112", "native_report_113", "native_report_114", "native_report_115", "native_report_116", "native_report_117", "native_report_118", "native_report_119",
    "native_report_120", "native_report_121", "native_report_122", "native_report_123", "native_report_124", "native_report_125", "native_report_126", "native_report_127",
    "native_report_128", "native_report_129", "native_report_130", "native_report_131", "native_report_132", "native_report_133", "native_report_134", "native_report_135",
    "native_report_136", "native_report_137", "native_report_138", "native_report_139", "native_report_140", "native_report_141", "native_report_142", "native_report_143",
    "native_report_144", "native_report_145", "native_report_146", "native_report_147", "native_report_148", "native_report_149", "native_report_150", "native_report_151",
    "native_report_152", "native_report_153", "native_report_154", "native_report_155", "native_report_156", "native_report_157", "native_report_158", "native_report_159",
    "native_report_160", "native_report_161", "native_report_162", "native_report_163", "native_report_164", "native_report_165", "native_report_166", "native_report_167",
    "native_report_168", "native_report_169", "native_report_170", "native_report_171", "native_report_172", "native_report_173", "native_report_174", "native_report_175",
    "native_report_176", "native_report_177", "native_report_178", "native_report_179", "native_report_180", "native_report_181", "native_report_182", "native_report_183",
    "native_report_184", "native_report_185", "native_report_186", "native_report_187", "native_report_188", "native_report_189", "native_report_190", "native_report_191",
    "native_report_192", "native_report_193", "native_report_194", "native_report_195", "native_report_196", "native_report_197", "native_report_198", "native_report_199",
    "native_report_200", "native_report_201", "native_report_202", "native_report_203", "native_report_204", "native_report_205", "native_report_206", "native_report_207",
    "native_report_208", "native_report_209", "native_report_210", "native_report_211", "native_report_212", "native_report_213", "native_report_214", "native_report_215",
    "native_report_216", "native_report_217", "native_report_218", "native_report_219", "native_report_220", "native_report_221", "native_report_222", "native_report_223",
    "native_report_224", "native_report_225", "native_report_226", "native_report_227", "native_report_228", "native_report_229", "native_report_230", "native_report_231",
    "native_report_232", "native_report_233", "native_report_234", "native_report_235", "native_report_236", "native_report_237", "native_report_238", "native_report_239",
    "native_report_240", "native_report_241", "native_report_242", "native_report_243", "native_report_244", "native_report_245", "native_report_246", "native_report_247",
    "native_report_248", "native_report_249", "native_report_250", "native_report_251", "native_report_252", "native_report_253", "native_report_254", "native_report_255",
    "native_report_256", "native_report_257", "native_report_258", "native_report_259", "native_report_260", "native_report_261", "native_report_262", "native_report_263",
    "native_report_264", "native_report_265", "native_report_266", "native_report_267", "native_report_268", "native_report_269", "native_report_270", "native_report_271",
    "native_report_272", "native_report_273", "native_report_274", "native_report_275", "native_report_276", "native_report_277",
];

pub(crate) fn native_report_id(path: &str) -> Option<NativeReportId> {
    NATIVE_REPORT_ROUTES
        .iter()
        .find_map(|route| (route.path == path).then_some(route.report_id))
}

pub(crate) fn native_report_key(report_id: NativeReportId) -> Option<&'static str> {
    NATIVE_REPORT_KEYS.get(usize::from(report_id.0)).copied()
}

#[cfg(test)]
pub(crate) fn registered_native_report_paths() -> impl Iterator<Item = &'static str> {
    NATIVE_REPORT_ROUTES.iter().map(|route| route.path)
}
