// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextRecallSelectedSnippet } from "./ContextRecallSelectedSnippet";
import type { ContextRecallSelectedSnippetSafety } from "./ContextRecallSelectedSnippetSafety";

export type ContextRecallSelectedSnippetEnvelope = { version: number, maxSnippets: number, maxSnippetChars: number, selectedSnippetCount: number, omittedSnippetCount: number, redactedSnippetCount: number, truncatedSnippetCount: number, snippets: Array<ContextRecallSelectedSnippet>, safety: ContextRecallSelectedSnippetSafety, };
