// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextRecallSelectedSnippetSafety = { readyForShadowHandoff: boolean, bounded: boolean, originIdentifiersExposed: boolean, rawRankedPayloadExposed: boolean, rankExplanationExposed: boolean, controlMarkerExposed: boolean, queryPayloadExposed: boolean, perOriginListExposed: boolean, };
