// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeptaChannelIngressEvidenceSummary = { events: bigint, receipts: bigint, pendingEvents: bigint, indeterminateEvents: bigint, };
