[package]
edition.workspace = true
license.workspace = true
name = "codex-hepta-nix-mnl-v1"
version.workspace = true
publish = false

[lib]
name = "codex_hepta_nix_mnl_v1"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-hepta-mnl-trust-v1 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
static_assertions = "1.1.0"
