use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs::File;
use std::fs::OpenOptions;
use std::io::Read;
use std::io::Write;
use std::path::Path;

use crate::ContractError;
use crate::Digest32;
use crate::P1_1B_CALLERS_RATCHET;
use crate::P1_1B_CONTEXT_ATTACHMENT;
use crate::P1_1B_DEFAULT_RECALL_CHANGED;
use crate::P1_1B_EXTERNAL_EFFECTS;
use crate::P1_1B_FEDERATION_RECALL_CHANGED;
use crate::P1_1B_MODEL_DOWNLOAD;
use crate::P1_1B_NETWORK_ACCESS;
use crate::P1_1B_OPERATOR_ACCEPTANCE;
use crate::P1_1B_PHYSICAL_SEND;
use crate::P1_1B_PRODUCTION_AUTHORITY;
use crate::P1_1B_PROMOTION;
use crate::P1_1B_REMOTE_EMBEDDING;
use crate::P1_1B_SCHEMA_VERSION;
use crate::digest::framed_digest;
use crate::embedding::EmbeddedVector;
use crate::embedding::EmbeddingMetric;
use crate::embedding::LocalEmbeddingDescriptor;
use crate::embedding::Q15_UNIT_NORM_SQUARED;
use crate::embedding::VectorQuantization;
use crate::embedding::vector_digest;
use crate::usize_to_u32;
use crate::usize_to_u64;
use crate::validate_id;

pub const MAX_INDEX_ITEMS: usize = 20_000;
pub const MAX_INDEX_FILE_BYTES: u64 = 512 * 1024 * 1024;
pub const MAX_SEARCH_RESULTS: usize = 64;
pub const MAX_SEARCH_CANDIDATES: usize = 4096;
const INDEX_MAGIC: &[u8; 8] = b"HPTANNB1";
const INDEX_NAMESPACE: &str = "hepta_intelligence_local_ann_index_v1";
const SCORE_SCALE_PPM: i128 = 1_000_000;

include!("index/types.rs");
include!("index/impl.rs");
include!("index/build.rs");
include!("index/search_math.rs");
include!("index/digests.rs");
include!("index/codec.rs");
include!("index/tests_module.rs");
