use codex_protocol::protocol::TurnContextCompressionStageKind;
use codex_protocol::protocol::TurnContextTier;

use super::entry::ContextSourceActivationGuard;
use super::entry::ContextSourceBudgetClass;
use super::entry::ContextSourcePrivacyClass;
use super::entry::ContextSourceQualityMetric;
use super::entry::ContextSourceRedactionPolicy;
use super::entry::ContextSourceRegistryEntry;
use super::entry::ContextSourceRollbackPolicy;
use super::entry::ContextSourceTrustClass;
use super::entry::ContextSourceTtl;
use super::entry::ContextSourceVolatility;

pub(super) const OWNER_LANE_HEPTA_CONTEXT: &str = "hepta-context";

const CONTEXT_SOURCE_REGISTRY_ENTRIES: &[ContextSourceRegistryEntry] = &[
    ContextSourceRegistryEntry {
        source_id: "apps",
        tier: TurnContextTier::Tool,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ToolInventory,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::RuntimeObserved,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::InventoryDigest,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::RebuildFromSource,
        omit_priority: Some(30),
        allowed_compression_actions: &[TurnContextCompressionStageKind::Defragment],
    },
    ContextSourceRegistryEntry {
        source_id: "available_plugins",
        tier: TurnContextTier::Tool,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ToolInventory,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::SystemOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::InventoryDigest,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::RebuildFromSource,
        omit_priority: Some(20),
        allowed_compression_actions: &[TurnContextCompressionStageKind::Defragment],
    },
    ContextSourceRegistryEntry {
        source_id: "available_skills",
        tier: TurnContextTier::Tool,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ToolInventory,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::SystemOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::InventoryDigest,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::RebuildFromSource,
        omit_priority: Some(40),
        allowed_compression_actions: &[TurnContextCompressionStageKind::Defragment],
    },
    ContextSourceRegistryEntry {
        source_id: "collaboration_mode",
        tier: TurnContextTier::Developer,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedDeveloper,
        ttl: ContextSourceTtl::Session,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::SystemOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::PolicyDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::RestorePrevious,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "context",
        tier: TurnContextTier::Runtime,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::FallbackContext,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::High,
        trust_class: ContextSourceTrustClass::RuntimeObserved,
        redaction_policy: ContextSourceRedactionPolicy::MetadataOnly,
        quality_metric: ContextSourceQualityMetric::Freshness,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "contextual_user",
        tier: TurnContextTier::User,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedUser,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::UserOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::Presence,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "developer_instructions",
        tier: TurnContextTier::Developer,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedDeveloper,
        ttl: ContextSourceTtl::Session,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::DeveloperOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::PolicyDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::NotMutable,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "environment",
        tier: TurnContextTier::Runtime,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::RuntimeState,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::High,
        trust_class: ContextSourceTrustClass::RuntimeObserved,
        redaction_policy: ContextSourceRedactionPolicy::MetadataOnly,
        quality_metric: ContextSourceQualityMetric::Freshness,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::RebuildFromSource,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "extension_contextual_user",
        tier: TurnContextTier::User,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedUser,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::ExtensionOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::ExtensionDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "extension_developer_capabilities",
        tier: TurnContextTier::Tool,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ToolCapability,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::ExtensionOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::ExtensionDigest,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: Some(10),
        allowed_compression_actions: &[TurnContextCompressionStageKind::Prune],
    },
    ContextSourceRegistryEntry {
        source_id: "extension_developer_policy",
        tier: TurnContextTier::Developer,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedDeveloper,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::ExtensionOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::ExtensionDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "extension_separate_developer",
        tier: TurnContextTier::Developer,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedDeveloper,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Medium,
        trust_class: ContextSourceTrustClass::ExtensionOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::ExtensionDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "model_switch",
        tier: TurnContextTier::SessionState,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::SessionState,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::SystemOwned,
        redaction_policy: ContextSourceRedactionPolicy::MetadataOnly,
        quality_metric: ContextSourceQualityMetric::Presence,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::RestorePrevious,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "non_text_content",
        tier: TurnContextTier::Runtime,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::NonTextContext,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::High,
        trust_class: ContextSourceTrustClass::RuntimeObserved,
        redaction_policy: ContextSourceRedactionPolicy::MetadataOnly,
        quality_metric: ContextSourceQualityMetric::Presence,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::DropTurnFragment,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "permissions",
        tier: TurnContextTier::System,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedSystem,
        ttl: ContextSourceTtl::Session,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::SystemOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::PolicyDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::NotMutable,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "personality",
        tier: TurnContextTier::Developer,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedDeveloper,
        ttl: ContextSourceTtl::Session,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::DeveloperOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::PolicyDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::RestorePrevious,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "realtime",
        tier: TurnContextTier::Runtime,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::RuntimeState,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::High,
        trust_class: ContextSourceTrustClass::RuntimeObserved,
        redaction_policy: ContextSourceRedactionPolicy::MetadataOnly,
        quality_metric: ContextSourceQualityMetric::Freshness,
        activation_guard: ContextSourceActivationGuard::CandidateOnly,
        rollback_policy: ContextSourceRollbackPolicy::RebuildFromSource,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
    ContextSourceRegistryEntry {
        source_id: "selected_context_recall",
        tier: TurnContextTier::RetrievedSnippets,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::BoundedRecallPayload,
        budget_class: ContextSourceBudgetClass::BoundedRecall,
        ttl: ContextSourceTtl::Turn,
        volatility: ContextSourceVolatility::High,
        trust_class: ContextSourceTrustClass::RetrievedMemory,
        redaction_policy: ContextSourceRedactionPolicy::GuardedEnvelope,
        quality_metric: ContextSourceQualityMetric::RecallQuality,
        activation_guard: ContextSourceActivationGuard::OperatorApprovalRequired,
        rollback_policy: ContextSourceRollbackPolicy::RerunRecall,
        omit_priority: Some(50),
        allowed_compression_actions: &[TurnContextCompressionStageKind::Summary],
    },
    ContextSourceRegistryEntry {
        source_id: "user_instructions",
        tier: TurnContextTier::User,
        owner_lane: OWNER_LANE_HEPTA_CONTEXT,
        privacy_class: ContextSourcePrivacyClass::PromptVisible,
        budget_class: ContextSourceBudgetClass::ProtectedUser,
        ttl: ContextSourceTtl::Session,
        volatility: ContextSourceVolatility::Low,
        trust_class: ContextSourceTrustClass::UserOwned,
        redaction_policy: ContextSourceRedactionPolicy::PromptHashOnly,
        quality_metric: ContextSourceQualityMetric::PolicyDigest,
        activation_guard: ContextSourceActivationGuard::Protected,
        rollback_policy: ContextSourceRollbackPolicy::RestorePrevious,
        omit_priority: None,
        allowed_compression_actions: &[],
    },
];

pub(crate) fn context_source_registry_entries() -> &'static [ContextSourceRegistryEntry] {
    CONTEXT_SOURCE_REGISTRY_ENTRIES
}

pub(crate) fn context_source_registry_entry(
    source_id: &str,
) -> Option<&'static ContextSourceRegistryEntry> {
    context_source_registry_entries()
        .iter()
        .find(|entry| entry.source_id == source_id)
}

pub(crate) fn source_aware_omit_priority(tier: TurnContextTier, source_id: &str) -> Option<u8> {
    let entry = context_source_registry_entry(source_id)?;
    if entry.tier == tier {
        entry.omit_priority
    } else {
        None
    }
}

pub(crate) fn source_aware_compression_kind(
    tier: TurnContextTier,
    source_id: &str,
) -> Option<TurnContextCompressionStageKind> {
    let entry = context_source_registry_entry(source_id)?;
    if entry.tier == tier {
        entry.default_compression_kind()
    } else {
        None
    }
}
