pub const CONTROL_UI_HEPTA_AGENT_LOGO_PNG_SHA256: &str = "eeaa030d321f566157055ae07d5f540bf06baeaaa6a2e6209227eb1bf6d3f41c";
pub const CONTROL_UI_HEPTA_AGENT_LOGO_PNG: &[u8] = include_bytes!("../../../apps/hepta-control-ui/assets/hepta-agent-logo.png");

// Generated by hepta-core/build.rs from the canonical base controller followed
// by the bounded, network-free v4 runtime controller. The generated SHA-256 and
// ETag describe the exact bytes served at /control-ui.js.
include!(concat!(env!("OUT_DIR"), "/control_ui_bundle_metadata.rs"));

pub const CONTROL_UI_BASE_JS: &[u8] =
    include_bytes!("../../../apps/hepta-control-ui/control-ui.js");
pub const CONTROL_UI_V4_RUNTIME_JS: &[u8] =
    include_bytes!("../../../apps/hepta-control-ui/control-ui-v4-runtime.js");
pub const CONTROL_UI_JS: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/control-ui.bundle.js"));
