// @generated by scripts/hepta-ui-light-glass-token-sync.rb; do not edit.
use makepad_widgets::*;

script_mod! {
    use mod.prelude.widgets.*
    use mod.widgets.*

    // Canonical Hepta light tempered-glass semantic palette.
    mod.widgets.COLOR_HEPTA_GLASS_ENVIRONMENT = #xEEF5F7FF
    mod.widgets.COLOR_HEPTA_GLASS_PANEL = #xE8EFF1F0
    mod.widgets.COLOR_HEPTA_GLASS_INPUT = #xF1F5F5F2
    mod.widgets.COLOR_HEPTA_GLASS_TEXT = #x142A32FF
    mod.widgets.COLOR_HEPTA_GLASS_MUTED = #x506575FF
    mod.widgets.COLOR_HEPTA_GLASS_DIM = #x566A78FF
    mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE = #xA5CCD7B8
    mod.widgets.COLOR_HEPTA_GLASS_FOCUS = #x0F7290FF
    mod.widgets.COLOR_HEPTA_GLASS_SECONDARY_ACCENT = #x14B8A6FF
    mod.widgets.COLOR_HEPTA_GLASS_ACTIVE_SURFACE = #xEAF7FCEE
    mod.widgets.COLOR_HEPTA_GLASS_SUCCESS = #x128A61FF
    mod.widgets.COLOR_HEPTA_GLASS_SHADOW = #x1730471F
    mod.widgets.COLOR_HEPTA_GLASS_GLOW = #x0F72901F

    // Compatibility aliases keep the Robrix substrate stable while both
    // product surfaces consume the same generated semantic values.
    mod.widgets.COLOR_ROBRIX_CYAN = (mod.widgets.COLOR_HEPTA_GLASS_SECONDARY_ACCENT)
    mod.widgets.COLOR_TELEGRAM_BG = (mod.widgets.COLOR_HEPTA_GLASS_ENVIRONMENT)
    mod.widgets.COLOR_TELEGRAM_PANEL = (mod.widgets.COLOR_HEPTA_GLASS_PANEL)
    mod.widgets.COLOR_TELEGRAM_INPUT = (mod.widgets.COLOR_HEPTA_GLASS_INPUT)
    mod.widgets.COLOR_TELEGRAM_BORDER = (mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE)
    mod.widgets.COLOR_TELEGRAM_TEXT = (mod.widgets.COLOR_HEPTA_GLASS_TEXT)
    mod.widgets.COLOR_TELEGRAM_MUTED = (mod.widgets.COLOR_HEPTA_GLASS_MUTED)
    mod.widgets.COLOR_TELEGRAM_DIM = (mod.widgets.COLOR_HEPTA_GLASS_DIM)
    mod.widgets.COLOR_TELEGRAM_BLUE = (mod.widgets.COLOR_HEPTA_GLASS_FOCUS)
    mod.widgets.COLOR_TELEGRAM_DIALOG_ACTIVE = (mod.widgets.COLOR_HEPTA_GLASS_ACTIVE_SURFACE)
    mod.widgets.COLOR_TELEGRAM_GREEN = (mod.widgets.COLOR_HEPTA_GLASS_SUCCESS)
    mod.widgets.COLOR_TELEGRAM_GLASS_HAIRLINE = (mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE)
    mod.widgets.COLOR_TELEGRAM_GLASS_SHADOW = (mod.widgets.COLOR_HEPTA_GLASS_SHADOW)

    mod.widgets.HEPTA_GLASS_CONTROL_RADIUS = 10.0
    mod.widgets.HEPTA_GLASS_PANEL_RADIUS = 16.0
    mod.widgets.HEPTA_GLASS_FLOATING_RADIUS = 18.0
}

/// Generated Rust-side compatibility value for non-Live widget code.
pub const COLOR_ROBRIX_CYAN: Vec4 = vec4(0.078431, 0.721569, 0.65098, 1.0);
