[package]
name = "hepta-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hepta-core.workspace = true
hepta-egress.workspace = true
hepta-runtime.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
hepta-plugins.workspace = true
tempfile.workspace = true
