// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted storage contract for a thread's canonical history.
 *
 * Legacy remains the default so binaries that predate paginated history keep
 * interpreting omitted metadata exactly as they do today. Callers must fail
 * closed before opening a paginated thread unless they implement that
 * contract end to end.
 */
export type ThreadHistoryMode = "legacy" | "paginated";
