#!/usr/bin/env python3
"""Read-only verifier/generator for the canonical Hepta V6 document system."""
from __future__ import annotations
import argparse, json, re, subprocess, sys
from collections import Counter, defaultdict, deque
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PLAN, STATUS, README = ROOT/'docs/DEVELOPMENT.md', ROOT/'docs/STATUS.md', ROOT/'README.md'
WORKFLOW = ROOT/'.github/workflows/hepta-development-docs.yml'
FILES = {
 'current':ROOT/'docs/CURRENT.json','system':ROOT/'docs/governance/DOCUMENT_SYSTEM.json',
 'architecture':ROOT/'docs/architecture/ARCHITECTURE.json','modules':ROOT/'docs/modules/MODULES.json',
 'work':ROOT/'docs/delivery/WORK_PACKAGES.json','development':ROOT/'docs/delivery/DEVELOPMENT_DAG.json',
 'activation':ROOT/'docs/delivery/ACTIVATION_DAG.json','evidence_dag':ROOT/'docs/delivery/EVIDENCE_DAG.json',
 'objectives':ROOT/'docs/control-plane/OBJECTIVES.json','evidence':ROOT/'docs/evidence/INDEX.json'}
SCHEMAS = {'current':'hepta.repository-current.v2','system':'hepta.document-system.v2',
 'architecture':'hepta.architecture-model.v3','modules':'hepta.module-registry.v2',
 'work':'hepta.work-package-registry.v2','development':'hepta.development-dag.v1',
 'activation':'hepta.activation-dag.v1','evidence_dag':'hepta.evidence-dag.v1',
 'objectives':'hepta.global-objective-registry.v1','evidence':'hepta.evidence-index.v2'}
REPO_ID, REPO, BRANCH = 1320694176,'TrillionniumFoundation/hepta-private-ci','integration/vnext-main-20260811'
PLAN_ID, PLAN_VERSION = 'HEPTA-GLOBAL-MODULAR-DEVELOPMENT-PLAN','6.0.0'
Q = ['source','staticVerification','exactHeadExecution','mergeCandidateExecution','semanticReview',
     'integration','runtimeActivation','physicalEvidence','independentReview','operatorAcceptance','promotion','release']

class DuplicateKeyError(ValueError): pass
def die(msg:str)->None: raise SystemExit('FAIL_HEPTA_DEVELOPMENT_DOCS: '+msg)
def need(ok:bool,msg:str)->None:
 if not ok: die(msg)
def pairs(items:list[tuple[str,Any]])->dict[str,Any]:
 out={}
 for key,value in items:
  if key in out: raise DuplicateKeyError(key)
  out[key]=value
 return out
def load(path:Path)->Any:
 try: return json.loads(path.read_text(),object_pairs_hook=pairs)
 except (OSError,UnicodeDecodeError,json.JSONDecodeError,DuplicateKeyError) as exc: die(f'{path.relative_to(ROOT)}: {exc}')
def false_tree(value:Any,label:str)->None:
 if isinstance(value,dict):
  for key,child in value.items(): false_tree(child,f'{label}.{key}')
 elif isinstance(value,bool): need(not value,f'positive flag {label}')
def tracked()->list[str]:
 try:
  raw=subprocess.run(['git','-C',str(ROOT),'ls-files','-z'],check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE).stdout
  return sorted(x.decode() for x in raw.split(b'\0') if x)
 except (OSError,subprocess.CalledProcessError):
  return sorted(str(x.relative_to(ROOT)).replace('\\','/') for x in ROOT.rglob('*') if x.is_file())
def legacy(system:dict[str,Any])->list[tuple[str,str]]:
 allowed=set(system.get('allowedDevelopmentPaths',[])); rules=[]
 for item in system.get('forbiddenLegacyPathRules',[]):
  need(item.get('id') and item.get('regex'),'invalid legacy rule')
  try: rules.append((item['id'],re.compile(item['regex'],re.I)))
  except re.error as exc: die(f"legacy regex {item['id']}: {exc}")
 out=[]
 for path in tracked():
  path=path.replace('\\','/')
  if path in allowed: continue
  if path.startswith('docs/archive/'): out.append((path,'in-tree-archive')); continue
  for name,pattern in rules:
   if pattern.search(path): out.append((path,name)); break
 return out
def acyclic(nodes:list[str],edges:list[dict[str,str]],label:str)->None:
 ns=set(nodes); degree={x:0 for x in ns}; outgoing=defaultdict(list); seen=set()
 for edge in edges:
  a,b=edge.get('from'),edge.get('to'); need(a in ns and b in ns and a!=b and (a,b) not in seen,f'{label} bad edge {a}->{b}')
  seen.add((a,b)); degree[b]+=1; outgoing[a].append(b)
 queue=deque(sorted(x for x,n in degree.items() if n==0)); visited=0
 while queue:
  a=queue.popleft(); visited+=1
  for b in sorted(outgoing[a]):
   degree[b]-=1
   if degree[b]==0: queue.append(b)
 need(visited==len(ns),f'{label} cycle')

def status_text(d:dict[str,Any])->str:
 c,w,m,e=d['current'],d['work'],d['modules'],d['evidence']; r=c['repository']; plan=c['developmentDocumentSet']
 lines=['# Hepta Current Development Status','',
  '> Generated by `python3 scripts/hepta-docs.py generate-status`. Do not edit by hand.','',
  f"**Observed:** `{c['observedAt']}`",f"**Authority:** `{c['authorityScope']}`; this projection grants no runtime, production, operator, promotion, or release authority.",
  f"**Canonical plan:** [`{plan['planId']}` v{plan['version']}](DEVELOPMENT.md)",'','## Repository baseline','','```text',
  f"repository_id = {r['id']}",f"repository = {r['fullName']}",f"default_branch = {r['defaultBranch']}",
  f"observed_head = {r['observedHead']}",f"observed_tree = {r['observedTree']}",'```','',
  f"Current work package: `{w['currentPackage']}`.",'','## Observed source candidates','',
  '| Candidate | PR | Head | Source / qualification posture |','|---|---:|---|---|']
 for x in c['activeCandidates']:
  q=x['qualification']; posture=f"source={q['source']}; exact={q['exactHeadExecution']}; semantic={q['semanticReview']}; activation={q['runtimeActivation']}"
  lines.append(f"| `{x['id']}` | #{x['pullRequest']} | `{x['head']}` | {posture} |")
 lines+=['','## Work-package state summary','','| State | Count |','|---|---:|']
 lines += [f'| `{state}` | {count} |' for state,count in sorted(Counter(x['state'] for x in w['packages']).items())]
 lines += ['','## Module and evidence inventory','',f"- Registered modules: **{len(m['modules'])}**",
  f"- Work packages: **{len(w['packages'])}**",f"- Time-bounded source observations: **{len(e['observations'])}**",
  '- Exact executable qualification, independent review, operator acceptance, promotion, and release remain distinct.','',
  '## Authority posture','',
  'Every authority flag is `false`. Queued, cancelled, runnerless, empty-step, source-only, generated, Draft-PR, fixture, or self-issued records are not PASS evidence.','']
 return '\n'.join(lines)

def verify()->int:
 for path in [PLAN,STATUS,README,WORKFLOW,*FILES.values()]: need(path.is_file(),f'missing {path.relative_to(ROOT)}')
 d={name:load(path) for name,path in FILES.items()}
 for name,schema in SCHEMAS.items(): need(d[name].get('schema')==schema,f'wrong schema {name}')
 c,s,a,m,w,o,e=d['current'],d['system'],d['architecture'],d['modules'],d['work'],d['objectives'],d['evidence']
 r=c.get('repository',{}); need((r.get('id'),r.get('fullName'),r.get('defaultBranch'))==(REPO_ID,REPO,BRANCH),'repository identity')
 datetime.fromisoformat(c['observedAt'].replace('Z','+00:00')); need(1<=int(c['staleAfterSeconds'])<=604800,'observation TTL')
 p=c.get('developmentDocumentSet',{}); need((p.get('planId'),p.get('version'),p.get('path'))==(PLAN_ID,PLAN_VERSION,'docs/DEVELOPMENT.md'),'current plan')
 need(s.get('canonicalHumanDevelopmentDocument')=='docs/DEVELOPMENT.md','document authority')
 for item,label in [(a,'architecture'),(m,'modules'),(w,'work')]: need((item.get('planId'),item.get('planVersion'))==(PLAN_ID,PLAN_VERSION),label+' plan')
 readme,plan,workflow=README.read_text(),PLAN.read_text(),WORKFLOW.read_text()
 need('docs/DEVELOPMENT.md' in readme and PLAN_ID in plan and PLAN_VERSION in plan,'human entry')
 need('pull_request:' in workflow and 'contents: read' in workflow and 'paths:' not in workflow and 'paths-ignore:' not in workflow,'workflow trigger/permission')
 for token in ['contents: write','git push','update-ref','pull-requests: write']: need(token not in workflow,'workflow mutation '+token)
 joined='\n'.join([readme,plan,*(x.read_text() for x in FILES.values())])
 for token in ['/Users/','/Volumes/','C:\\Users\\']: need(token not in joined,'host-local path '+token)
 hits=legacy(s); need(not hits,'legacy paths: '+', '.join(f'{x} ({y})' for x,y in hits[:20]))
 for name in d: false_tree(d[name].get('authorityFlags'),name+'.authorityFlags')
 false_tree(c.get('evidenceRules'),'current.evidenceRules')
 need(all(x=='not_issued' for x in c.get('externalGates',{}).values()),'current external gate')
 need(all(x=='not_issued' for x in e.get('externalGates',{}).values()),'evidence external gate')
 candidate_ids=set()
 for x in c.get('activeCandidates',[]):
  ident,q=x.get('id'),x.get('qualification'); need(ident and ident not in candidate_ids,'candidate id'); candidate_ids.add(ident)
  need(isinstance(q,dict) and list(q)==Q,'qualification vector '+str(ident))
  need(q['runtimeActivation']=='not_allowed' and q['operatorAcceptance']==q['promotion']==q['release']=='not_issued','candidate authority '+ident)
 module_ids=set(); roots={}; writers={}
 for x in m.get('modules',[]):
  ident=x.get('id'); need(ident and ident not in module_ids,'module id'); module_ids.add(ident)
  need(x.get('owner') and x.get('deputy') and x.get('roots'),'module ownership '+ident)
  for root in x['roots']: need(root not in roots,'source root '+root); roots[root]=ident
  for domain in x.get('writes',[]): need(domain not in writers,'writer '+domain); writers[domain]=ident
 for x in m['modules']:
  for dep in x.get('uses',[]): need(dep in module_ids,f"module dep {x['id']}->{dep}")
 package_ids=set()
 for x in w.get('packages',[]):
  ident=x.get('id'); need(ident and ident not in package_ids,'package id'); package_ids.add(ident)
  need(x.get('module') in module_ids and x.get('done'),'package '+ident)
 need(w.get('currentPackage') in package_ids,'current package')
 for x in w['packages']:
  for field in ['developmentAfter','activationAfter','evidenceAfter']:
   for dep in x.get(field,[]): need(dep in package_ids,f"{field} {x['id']}->{dep}")
 for name,field in [('development','developmentAfter'),('activation','activationAfter')]:
  dag=d[name]; need(set(dag.get('nodes',[]))==package_ids,name+' nodes')
  expected={(dep,x['id']) for x in w['packages'] for dep in x.get(field,[])}; actual={(x.get('from'),x.get('to')) for x in dag.get('edges',[])}
  need(expected==actual,name+' edges'); acyclic(dag['nodes'],dag['edges'],name)
 acyclic(d['evidence_dag'].get('nodes',[]),d['evidence_dag'].get('edges',[]),'evidence_dag')
 hard=set()
 for x in o.get('hardConstraints',[]): need(x.get('id') and x['id'] not in hard,'hard constraint'); hard.add(x['id'])
 for group in o.get('objectiveSets',[]):
  entries=group.get('objectives',[]); need(entries and len({x.get('id') for x in entries})==len(entries),'objective ids')
  need(abs(sum(float(x.get('weight',-1)) for x in entries)-1)<1e-9,'objective weights')
  need(all(x.get('direction') in {'maximize','minimize'} for x in entries),'objective direction')
 auth=o.get('optimizerAuthority',{}); need(auth.get('maySelectPlan') is True,'optimizer select')
 need(all(auth.get(x) is False for x in ['mayIssueCapability','mayExecutePhysicalEffect','maySelfAccept','mayPromoteOrRelease']),'optimizer authority')
 need(e.get('qualificationDimensions')==Q,'evidence dimensions'); observations=e.get('observations',[])
 need({x.get('candidateId') for x in observations}==candidate_ids,'evidence coverage')
 for x in observations:
  for key in ['terminalExecutablePass','semanticQualificationAccepted','operatorAccepted','promoted','released']: need(x.get(key) is False,f"evidence {x.get('candidateId')}.{key}")
 need(STATUS.read_text()==status_text(d),'STATUS.md stale')
 print('PASS_HEPTA_DEVELOPMENT_DOCS_V6'); return 0

def generate()->int:
 STATUS.write_text(status_text({name:load(path) for name,path in FILES.items()})); print('WROTE docs/STATUS.md'); return 0
def inventory()->int:
 hits=legacy(load(FILES['system'])); print(json.dumps({'schema':'hepta.legacy-development-document-inventory.v1','count':len(hits),'matches':[{'path':p,'rule':r} for p,r in hits]},indent=2)); return 1 if hits else 0
def main()->int:
 parser=argparse.ArgumentParser(); sub=parser.add_subparsers(dest='command',required=True)
 for name in ['verify','generate-status','inventory-legacy']: sub.add_parser(name)
 cmd=parser.parse_args().command
 return verify() if cmd=='verify' else generate() if cmd=='generate-status' else inventory()
if __name__=='__main__':
 try: raise SystemExit(main())
 except BrokenPipeError: sys.exit(1)
