#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "pathname"

ROOT = Pathname.new(__dir__).join("..").expand_path
SOURCE = ROOT.join("design-tokens/hepta-light-glass.tokens.json")
CSS_OUTPUT = ROOT.join("apps/hepta-control-ui/light-glass-tokens.generated.css")
RUST_OUTPUT = ROOT.join("apps/hepta-native/src/shared/light_glass_tokens.rs")

tokens = JSON.parse(SOURCE.read)
colors = tokens.fetch("color")
radii = tokens.fetch("radius")
motion = tokens.fetch("motion")

required_colors = %w[
  environment panel input text muted dim hairline focus secondaryAccent
  activeSurface success glassShadow glassGlow
]
missing_colors = required_colors.reject { |key| colors.key?(key) }
abort("missing color tokens: #{missing_colors.join(', ')}") unless missing_colors.empty?

def css_color(value)
  value.downcase
end

def makepad_color(value)
  normalized = value.delete_prefix("#").upcase
  raise "invalid RGBA token #{value.inspect}" unless normalized.match?(/\A[0-9A-F]{8}\z/)

  "#x#{normalized}"
end

def vec4_color(value)
  bytes = value.delete_prefix("#").scan(/../).map { |part| part.to_i(16) }
  raise "invalid RGBA token #{value.inspect}" unless bytes.length == 4

  channels = bytes.map { |byte| format("%.6f", byte / 255.0).sub(/0+\z/, "").sub(/\.\z/, ".0") }
  "vec4(#{channels.join(', ')})"
end

css = <<~CSS
  /* @generated by scripts/hepta-ui-light-glass-token-sync.rb; do not edit. */
  :root {
    --hepta-glass-environment: #{css_color(colors.fetch('environment'))};
    --hepta-glass-panel: #{css_color(colors.fetch('panel'))};
    --hepta-glass-input: #{css_color(colors.fetch('input'))};
    --hepta-glass-text: #{css_color(colors.fetch('text'))};
    --hepta-glass-muted: #{css_color(colors.fetch('muted'))};
    --hepta-glass-dim: #{css_color(colors.fetch('dim'))};
    --hepta-glass-hairline: #{css_color(colors.fetch('hairline'))};
    --hepta-glass-focus: #{css_color(colors.fetch('focus'))};
    --hepta-glass-secondary-accent: #{css_color(colors.fetch('secondaryAccent'))};
    --hepta-glass-active-surface: #{css_color(colors.fetch('activeSurface'))};
    --hepta-glass-success: #{css_color(colors.fetch('success'))};
    --hepta-glass-shadow: #{css_color(colors.fetch('glassShadow'))};
    --hepta-glass-glow: #{css_color(colors.fetch('glassGlow'))};
    --hepta-glass-control-radius: #{Integer(radii.fetch('control'))}px;
    --hepta-glass-panel-radius: #{Integer(radii.fetch('panel'))}px;
    --hepta-glass-floating-radius: #{Integer(radii.fetch('floating'))}px;
    --hepta-glass-motion-fast: #{Integer(motion.fetch('fastMs'))}ms;
    --hepta-glass-motion-normal: #{Integer(motion.fetch('normalMs'))}ms;
  }

  html[data-theme-mode="light"] {
    color-scheme: light;
    --bg: var(--hepta-glass-environment);
    --bg-elevated: #f7fafb;
    --bg-hover: var(--hepta-glass-active-surface);
    --card: var(--hepta-glass-panel);
    --card-foreground: var(--hepta-glass-text);
    --popover: var(--hepta-glass-input);
    --panel: var(--hepta-glass-panel);
    --panel-strong: var(--hepta-glass-input);
    --panel-hover: var(--hepta-glass-active-surface);
    --chrome: var(--hepta-glass-panel);
    --chrome-strong: var(--hepta-glass-input);
    --text: var(--hepta-glass-text);
    --text-strong: #0b222b;
    --chat-text: var(--hepta-glass-text);
    --muted: var(--hepta-glass-muted);
    --muted-strong: #344e59;
    --muted-foreground: var(--hepta-glass-muted);
    --border: var(--hepta-glass-hairline);
    --border-strong: color-mix(in srgb, var(--hepta-glass-focus) 38%, var(--hepta-glass-hairline));
    --border-hover: var(--hepta-glass-focus);
    --input: var(--hepta-glass-input);
    --ring: var(--hepta-glass-focus);
    --accent: var(--hepta-glass-focus);
    --accent-hover: #0a667b;
    --accent-muted: color-mix(in srgb, var(--hepta-glass-focus) 72%, transparent);
    --accent-subtle: color-mix(in srgb, var(--hepta-glass-focus) 10%, transparent);
    --accent-glow: var(--hepta-glass-glow);
    --primary: var(--hepta-glass-focus);
    --primary-foreground: #ffffff;
    --secondary: var(--hepta-glass-panel);
    --secondary-foreground: var(--hepta-glass-text);
    --accent-2: var(--hepta-glass-secondary-accent);
    --ok: var(--hepta-glass-success);
    --focus: color-mix(in srgb, var(--hepta-glass-focus) 22%, transparent);
    --grid-line: color-mix(in srgb, var(--hepta-glass-focus) 5%, transparent);
    --shadow-sm: 0 1px 2px var(--hepta-glass-shadow);
    --shadow-md: 0 4px 14px var(--hepta-glass-shadow);
    --shadow-lg: 0 12px 30px var(--hepta-glass-shadow);
    --shadow-xl: 0 20px 42px var(--hepta-glass-shadow);
    --radius-md: var(--hepta-glass-control-radius);
    --radius-lg: var(--hepta-glass-panel-radius);
    --radius-xl: var(--hepta-glass-floating-radius);
    --duration-fast: var(--hepta-glass-motion-fast);
    --duration-normal: var(--hepta-glass-motion-normal);
  }
CSS

rust = <<~RUST
  // @generated by scripts/hepta-ui-light-glass-token-sync.rb; do not edit.
  use makepad_widgets::*;

  script_mod! {
      use mod.prelude.widgets.*
      use mod.widgets.*

      // Canonical Hepta light tempered-glass semantic palette.
      mod.widgets.COLOR_HEPTA_GLASS_ENVIRONMENT = #{makepad_color(colors.fetch('environment'))}
      mod.widgets.COLOR_HEPTA_GLASS_PANEL = #{makepad_color(colors.fetch('panel'))}
      mod.widgets.COLOR_HEPTA_GLASS_INPUT = #{makepad_color(colors.fetch('input'))}
      mod.widgets.COLOR_HEPTA_GLASS_TEXT = #{makepad_color(colors.fetch('text'))}
      mod.widgets.COLOR_HEPTA_GLASS_MUTED = #{makepad_color(colors.fetch('muted'))}
      mod.widgets.COLOR_HEPTA_GLASS_DIM = #{makepad_color(colors.fetch('dim'))}
      mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE = #{makepad_color(colors.fetch('hairline'))}
      mod.widgets.COLOR_HEPTA_GLASS_FOCUS = #{makepad_color(colors.fetch('focus'))}
      mod.widgets.COLOR_HEPTA_GLASS_SECONDARY_ACCENT = #{makepad_color(colors.fetch('secondaryAccent'))}
      mod.widgets.COLOR_HEPTA_GLASS_ACTIVE_SURFACE = #{makepad_color(colors.fetch('activeSurface'))}
      mod.widgets.COLOR_HEPTA_GLASS_SUCCESS = #{makepad_color(colors.fetch('success'))}
      mod.widgets.COLOR_HEPTA_GLASS_SHADOW = #{makepad_color(colors.fetch('glassShadow'))}
      mod.widgets.COLOR_HEPTA_GLASS_GLOW = #{makepad_color(colors.fetch('glassGlow'))}

      // Compatibility aliases keep the Robrix substrate stable while both
      // product surfaces consume the same generated semantic values.
      mod.widgets.COLOR_ROBRIX_CYAN = (mod.widgets.COLOR_HEPTA_GLASS_SECONDARY_ACCENT)
      mod.widgets.COLOR_TELEGRAM_BG = (mod.widgets.COLOR_HEPTA_GLASS_ENVIRONMENT)
      mod.widgets.COLOR_TELEGRAM_PANEL = (mod.widgets.COLOR_HEPTA_GLASS_PANEL)
      mod.widgets.COLOR_TELEGRAM_INPUT = (mod.widgets.COLOR_HEPTA_GLASS_INPUT)
      mod.widgets.COLOR_TELEGRAM_BORDER = (mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE)
      mod.widgets.COLOR_TELEGRAM_TEXT = (mod.widgets.COLOR_HEPTA_GLASS_TEXT)
      mod.widgets.COLOR_TELEGRAM_MUTED = (mod.widgets.COLOR_HEPTA_GLASS_MUTED)
      mod.widgets.COLOR_TELEGRAM_DIM = (mod.widgets.COLOR_HEPTA_GLASS_DIM)
      mod.widgets.COLOR_TELEGRAM_BLUE = (mod.widgets.COLOR_HEPTA_GLASS_FOCUS)
      mod.widgets.COLOR_TELEGRAM_DIALOG_ACTIVE = (mod.widgets.COLOR_HEPTA_GLASS_ACTIVE_SURFACE)
      mod.widgets.COLOR_TELEGRAM_GREEN = (mod.widgets.COLOR_HEPTA_GLASS_SUCCESS)
      mod.widgets.COLOR_TELEGRAM_GLASS_HAIRLINE = (mod.widgets.COLOR_HEPTA_GLASS_HAIRLINE)
      mod.widgets.COLOR_TELEGRAM_GLASS_SHADOW = (mod.widgets.COLOR_HEPTA_GLASS_SHADOW)

      mod.widgets.HEPTA_GLASS_CONTROL_RADIUS = #{Integer(radii.fetch('control'))}.0
      mod.widgets.HEPTA_GLASS_PANEL_RADIUS = #{Integer(radii.fetch('panel'))}.0
      mod.widgets.HEPTA_GLASS_FLOATING_RADIUS = #{Integer(radii.fetch('floating'))}.0
  }

  /// Generated Rust-side compatibility value for non-Live widget code.
  pub const COLOR_ROBRIX_CYAN: Vec4 = #{vec4_color(colors.fetch('secondaryAccent'))};
RUST

outputs = { CSS_OUTPUT => css, RUST_OUTPUT => rust }
if ARGV == ["--check"]
  stale = outputs.each_with_object([]) do |(path, expected), paths|
    paths << path.to_s unless path.file? && path.read == expected
  end
  abort("generated light-glass tokens are stale: #{stale.join(', ')}") unless stale.empty?
  puts "hepta light-glass tokens: ready"
elsif ARGV.empty?
  outputs.each { |path, content| path.write(content) }
  puts "updated #{outputs.length} generated light-glass token files"
else
  abort("usage: #{File.basename($PROGRAM_NAME)} [--check]")
end
