#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

bash "$repo_root/scripts/hepta-context-release-manifest-gate.sh"
bash "$repo_root/scripts/hepta-context-manifest-replay-hash-boundary-gate.sh"
bash "$repo_root/scripts/hepta-context-source-registry-catalog-gate.sh"
bash "$repo_root/scripts/hepta-context-source-registry-rust-gate.sh"
bash "$repo_root/scripts/hepta-context-source-registry-health-gate.sh"
bash "$repo_root/scripts/hepta-context-health-gate.sh"
bash "$repo_root/scripts/hepta-context-adaptive-budget-allocation-report-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-snapshot-helper-boundary-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-test-module-boundary-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-recall-helper-boundary-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-recall-manifest-payload-light-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-taxonomy-report-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-formation-receipt-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-formation-queue-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-formation-candidate-no-leak-export-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-temporal-fact-schema-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-temporal-fact-graph-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-eval-harness-seed-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-adaptive-allocator-eval-shadow-gate.sh"
bash "$repo_root/scripts/hepta-context-memory-recall-quality-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-status-report-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-activation-blocker-matrix-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-negative-export-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-canonical-export-digest-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-digest-tamper-matrix-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-freshness-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-freshness-dependency-chain-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-freshness-dependency-chain-canonical-digest-gate.sh"
bash "$repo_root/scripts/hepta-context-plane-operator-approval-packet-freshness-dependency-chain-expiry-drift-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-negative-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-fixture-matrix-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-negative-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-precheck-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-idempotence-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-atomic-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-writability-precheck-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-symlink-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-report-status-artifact-export-hardlink-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-front-door-gate-list-parity-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-readiness-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-operator-approval-evidence-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-readiness-export-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-activation-negative-matrix-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-activation-surface-audit.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-leak-bait-gate.sh"
bash "$repo_root/scripts/hepta-context-selected-snippet-live-prompt-compression-gate.sh"
bash "$repo_root/scripts/hepta-context-runtime-provider-rollup-manifest-handoff-gate.sh"
bash "$repo_root/scripts/hepta-context-selected-snippet-api-surface-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-positive-route-readiness-gate.sh"
bash "$repo_root/scripts/hepta-context-source-aware-compression-positive-route-change-detector.sh"
"$repo_root/scripts/hepta-context-response-debug-export-gate.sh"
"$repo_root/scripts/hepta-context-prompt-input-summary-gate.sh"
bash "$repo_root/scripts/hepta-context-selected-recall-summary-canary-gate.sh"
bash "$repo_root/scripts/hepta-context-selected-recall-summary-canary-eval-gate.sh"

echo "Hepta context debug gate passed"
