#![forbid(unsafe_code)]

mod canonical;
mod channel;
mod identity;
mod memory;
mod memory_mutation;
mod memory_mutation_evidence;
mod migration;
mod provider;
mod receipt;
mod stable_id;

pub use channel::CHANNEL_EVIDENCE_SCHEMA_VERSION;
pub use channel::ChannelAdapterId;
pub use channel::ChannelIngressEvent;
pub use channel::ChannelIngressEventId;
pub use channel::ChannelIngressReceipt;
pub use channel::ChannelIngressReceiptId;
pub use channel::ChannelIngressTerminal;
pub use channel::ChannelScope;
pub use channel::channel_target_thread_sha256;
pub use channel::validate_ingress_event;
pub use channel::validate_ingress_receipt;
pub use identity::ActionId;
pub use identity::DecisionId;
pub use identity::ReceiptId;
pub use memory::AttachmentTrust;
pub use memory::CrossThreadScope;
pub use memory::MEMORY_CONTRACT_SCHEMA_VERSION;
pub use memory::MemoryAttachmentMetadata;
pub use memory::MemoryId;
pub use memory::MemoryLifecycle;
pub use memory::MemoryProvenance;
pub use memory::MemoryRevision;
pub use memory::MemoryScope;
pub use memory::MemorySourceKind;
pub use memory::QueryFingerprint;
pub use memory::RankedMemoryRef;
pub use memory::RecallAuthority;
pub use memory::RecallEligibility;
pub use memory::RecallLimits;
pub use memory::RecallRequest;
pub use memory::RecallRequestId;
pub use memory::RecallScorePpm;
pub use memory::RevisionStamp;
pub use memory::SCORE_SCALE_PPM;
pub use memory_mutation::MEMORY_MUTATION_SCHEMA_VERSION;
pub use memory_mutation::MemoryMutationOperation;
pub use memory_mutation::MemoryMutationProposal;
pub use memory_mutation::MemoryMutationProposalId;
pub use memory_mutation::MemoryMutationReasonCode;
pub use memory_mutation_evidence::MEMORY_MUTATION_DRY_RUN_SCHEMA_VERSION;
pub use memory_mutation_evidence::MemoryMutationDryRun;
pub use memory_mutation_evidence::MemoryMutationDryRunDisposition;
pub use memory_mutation_evidence::MemoryMutationDryRunId;
pub use memory_mutation_evidence::MemoryMutationDryRunReason;
pub use memory_mutation_evidence::canonical_memory_mutation_dry_run;
pub use migration::MAX_MIGRATION_FAMILY_ID_BYTES;
pub use migration::MIGRATION_SNAPSHOT_SCHEMA_VERSION;
pub use migration::MigrationDisposition;
pub use migration::MigrationFamilyId;
pub use migration::MigrationFamilySnapshot;
pub use migration::MigrationSnapshotId;
pub use provider::PROVIDER_EVIDENCE_SCHEMA_VERSION;
pub use provider::ProviderAttemptId;
pub use provider::ProviderInvocationIntent;
pub use provider::ProviderInvocationReceipt;
pub use provider::ProviderReceiptId;
pub use provider::ProviderRequestBinding;
pub use provider::ProviderRequestKind;
pub use provider::ProviderTerminal;
pub use provider::ProviderTransport;
pub use provider::RequestBindingId;
pub use receipt::GOVERNANCE_SCHEMA_VERSION;
pub use receipt::GovernanceDecision;
pub use receipt::GovernanceDecisionRecord;
pub use receipt::GovernanceMode;
pub use receipt::GovernanceReceipt;
pub use receipt::HandlerOutcome;
pub use receipt::PolicyPhase;
pub use receipt::PolicyStamp;
pub use receipt::Sha256Digest;
pub use receipt::ToolAction;
pub use receipt::ToolActionSource;
